// go:build testing
package main

// Code generated by gitverse.ru/sbertech/ignite-go-client/tools/generator DO NOT EDIT.

import (
	"context"

	"gitverse.ru/sbertech/ignite-go-client"
)

func (o *BinarylizablePersonKey) TypeName() string {
	return "PERSON_KEY"
}

func (o *BinarylizablePersonKey) Platform() ignite.MarshallerPlatform {
	return ignite.JavaMarshaller
}

func (o *BinarylizablePersonKey) Write(ctx context.Context, writer ignite.BinaryWriter) error {
	if err := writer.WriteField(ctx, "id", o.identifier); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "organization_id", o.organization); err != nil {
		return err
	}
	return nil
}

func (o *BinarylizablePersonKey) AffinityKeyName() string {
	return "organization_id"
}

func (o *BinarylizablePersonKey) Read(ctx context.Context, reader ignite.BinaryReader) error {
	{
		var tmp int64
		if err := reader.ReadField(ctx, "id", &tmp); err != nil {
			return err
		}
		o.identifier = int(tmp)
	}
	if err := reader.ReadField(ctx, "organization_id", &o.organization); err != nil {
		return err
	}
	return nil
}

func (o *Employee) TypeName() string {
	return "EMPLOYEE"
}

func (o *Employee) Platform() ignite.MarshallerPlatform {
	return ignite.JavaMarshaller
}

func (o *Employee) Write(ctx context.Context, writer ignite.BinaryWriter) error {
	if err := writer.WriteField(ctx, "name", o.name); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "salary", o.salary); err != nil {
		return err
	}
	return nil
}

func (o *Employee) Read(ctx context.Context, reader ignite.BinaryReader) error {
	if err := reader.ReadField(ctx, "name", &o.name); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "salary", &o.salary); err != nil {
		return err
	}
	return nil
}

func RegisterMainIgniteTypes(cli *ignite.Client) error {
	if err := ignite.RegisterType[*BinarylizablePersonKey](cli); err != nil {
		return err
	}
	if err := ignite.RegisterType[*Employee](cli); err != nil {
		return err
	}
	return nil
}
