// Code generated by "stringer -type=ClusterState"; DO NOT EDIT.

package ignite

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Inactive-0]
	_ = x[Active-1]
	_ = x[ActiveReadOnly-2]
}

const _ClusterState_name = "InactiveActiveActiveReadOnly"

var _ClusterState_index = [...]uint8{0, 8, 14, 28}

func (i ClusterState) String() string {
	if i < 0 || i >= ClusterState(len(_ClusterState_index)-1) {
		return "ClusterState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ClusterState_name[_ClusterState_index[i]:_ClusterState_index[i+1]]
}
