// Code generated by "stringer -type=CollectionKind,MapKind"; DO NOT EDIT.

package ignite

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UserSet - -1]
	_ = x[UserCollection-0]
	_ = x[ArrayList-1]
	_ = x[LinkedList-2]
	_ = x[HashSet-3]
	_ = x[LinkedHashSet-4]
	_ = x[SingletonList-5]
}

const _CollectionKind_name = "UserSetUserCollectionArrayListLinkedListHashSetLinkedHashSetSingletonList"

var _CollectionKind_index = [...]uint8{0, 7, 21, 30, 40, 47, 60, 73}

func (i CollectionKind) String() string {
	i -= -1
	if i < 0 || i >= CollectionKind(len(_CollectionKind_index)-1) {
		return "CollectionKind(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _CollectionKind_name[_CollectionKind_index[i]:_CollectionKind_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UserMap-0]
	_ = x[HashMap-1]
	_ = x[LinkedHashMap-2]
}

const _MapKind_name = "UserMapHashMapLinkedHashMap"

var _MapKind_index = [...]uint8{0, 7, 14, 27}

func (i MapKind) String() string {
	if i < 0 || i >= MapKind(len(_MapKind_index)-1) {
		return "MapKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MapKind_name[_MapKind_index[i]:_MapKind_index[i+1]]
}
