// Code generated by "stringer -type=TypeDesc"; DO NOT EDIT.

package ignite

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[optimizedMarshallerObjectType - -2]
	_ = x[objectType - -1]
	_ = x[unregisteredType-0]
	_ = x[ByteType-1]
	_ = x[ShortType-2]
	_ = x[IntType-3]
	_ = x[LongType-4]
	_ = x[FloatType-5]
	_ = x[DoubleType-6]
	_ = x[CharType-7]
	_ = x[BoolType-8]
	_ = x[StringType-9]
	_ = x[UuidType-10]
	_ = x[DateType-11]
	_ = x[ByteArrayType-12]
	_ = x[ShortArrayType-13]
	_ = x[IntArrayType-14]
	_ = x[LongArrayType-15]
	_ = x[FloatArrayType-16]
	_ = x[DoubleArrayType-17]
	_ = x[CharArrayType-18]
	_ = x[BoolArrayType-19]
	_ = x[StringArrayType-20]
	_ = x[UuidArrayType-21]
	_ = x[DateArrayType-22]
	_ = x[ObjectArrayType-23]
	_ = x[CollectionType-24]
	_ = x[MapType-25]
	_ = x[wrappedObjectType-27]
	_ = x[EnumType-28]
	_ = x[EnumArrayType-29]
	_ = x[DecimalType-30]
	_ = x[DecimalArrayType-31]
	_ = x[ClassType-32]
	_ = x[TimestampType-33]
	_ = x[TimestampArrayType-34]
	_ = x[proxyType-35]
	_ = x[TimeType-36]
	_ = x[TimeArrayType-37]
	_ = x[BinaryEnumType-38]
	_ = x[NullType-101]
	_ = x[handleType-102]
	_ = x[BinaryObjectType-103]
}

const (
	_TypeDesc_name_0 = "optimizedMarshallerObjectTypeobjectTypeunregisteredTypeByteTypeShortTypeIntTypeLongTypeFloatTypeDoubleTypeCharTypeBoolTypeStringTypeUuidTypeDateTypeByteArrayTypeShortArrayTypeIntArrayTypeLongArrayTypeFloatArrayTypeDoubleArrayTypeCharArrayTypeBoolArrayTypeStringArrayTypeUuidArrayTypeDateArrayTypeObjectArrayTypeCollectionTypeMapType"
	_TypeDesc_name_1 = "wrappedObjectTypeEnumTypeEnumArrayTypeDecimalTypeDecimalArrayTypeClassTypeTimestampTypeTimestampArrayTypeproxyTypeTimeTypeTimeArrayTypeBinaryEnumType"
	_TypeDesc_name_2 = "NullTypehandleTypeBinaryObjectType"
)

var (
	_TypeDesc_index_0 = [...]uint16{0, 29, 39, 55, 63, 72, 79, 87, 96, 106, 114, 122, 132, 140, 148, 161, 175, 187, 200, 214, 229, 242, 255, 270, 283, 296, 311, 325, 332}
	_TypeDesc_index_1 = [...]uint8{0, 17, 25, 38, 49, 65, 74, 87, 105, 114, 122, 135, 149}
	_TypeDesc_index_2 = [...]uint8{0, 8, 18, 34}
)

func (i TypeDesc) String() string {
	switch {
	case -2 <= i && i <= 25:
		i -= -2
		return _TypeDesc_name_0[_TypeDesc_index_0[i]:_TypeDesc_index_0[i+1]]
	case 27 <= i && i <= 38:
		i -= 27
		return _TypeDesc_name_1[_TypeDesc_index_1[i]:_TypeDesc_index_1[i+1]]
	case 101 <= i && i <= 103:
		i -= 101
		return _TypeDesc_name_2[_TypeDesc_index_2[i]:_TypeDesc_index_2[i+1]]
	default:
		return "TypeDesc(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
