// Code generated by "stringer -type=TypeDesc"; DO NOT EDIT.

package ignite

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[String-9]
	_ = x[Uuid-10]
	_ = x[ByteArray-12]
	_ = x[ShortArray-13]
	_ = x[IntArray-14]
	_ = x[LongArray-15]
	_ = x[FloatArray-16]
	_ = x[DoubleArray-17]
	_ = x[CharArray-18]
	_ = x[BooleanArray-19]
	_ = x[StringArray-20]
	_ = x[Map-25]
	_ = x[Null-101]
}

const (
	_TypeDesc_name_0 = "StringUuid"
	_TypeDesc_name_1 = "ByteArrayShortArrayIntArrayLongArrayFloatArrayDoubleArrayCharArrayBooleanArrayStringArray"
	_TypeDesc_name_2 = "Map"
	_TypeDesc_name_3 = "Null"
)

var (
	_TypeDesc_index_0 = [...]uint8{0, 6, 10}
	_TypeDesc_index_1 = [...]uint8{0, 9, 19, 27, 36, 46, 57, 66, 78, 89}
)

func (i TypeDesc) String() string {
	switch {
	case 9 <= i && i <= 10:
		i -= 9
		return _TypeDesc_name_0[_TypeDesc_index_0[i]:_TypeDesc_index_0[i+1]]
	case 12 <= i && i <= 20:
		i -= 12
		return _TypeDesc_name_1[_TypeDesc_index_1[i]:_TypeDesc_index_1[i+1]]
	case i == 25:
		return _TypeDesc_name_2
	case i == 101:
		return _TypeDesc_name_3
	default:
		return "TypeDesc(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
