// go:build testing
package test_binarylizable

// Code generated by gitverse.ru/sbertech/ignite-go-client/tools/generator DO NOT EDIT.

import (
	"context"
	"fmt"

	"github.com/cockroachdb/apd/v3"
	"github.com/google/uuid"
	"gitverse.ru/sbertech/ignite-go-client"
	ign "gitverse.ru/sbertech/ignite-go-client"
)

func (o *ObjectArrays) Platform() ign.MarshallerPlatform {
	return ign.JavaMarshaller
}

func (o *ObjectArrays) Write(ctx context.Context, writer ign.BinaryWriter) error {
	if err := writer.WriteField(ctx, "ifaceArray", o.ifaceArray); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "boArray", o.boArray); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "binArray", o.binArray); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "simpleStructArray", o.simpleStructArray); err != nil {
		return err
	}
	return nil
}

func (o *ObjectArrays) Read(ctx context.Context, reader ign.BinaryReader) error {
	if err := reader.ReadField(ctx, "ifaceArray", &o.ifaceArray); err != nil {
		return err
	}
	{
		var tmp []interface{}
		if err := reader.ReadField(ctx, "boArray", &tmp); err != nil {
			return err
		}
		if tmp != nil {
			o.boArray = make([]ign.BinaryObject, 0, len(tmp))
			for _, el0 := range tmp {
				var el ign.BinaryObject = nil
				if el0 != nil {
					var ok bool
					el, ok = el0.(ign.BinaryObject)
					if !ok {
						return fmt.Errorf("failed to convert %v to ign.BinaryObject", el0)
					}
				}
				o.boArray = append(o.boArray, el)
			}
		}
	}
	{
		var tmp []interface{}
		if err := reader.ReadField(ctx, "binArray", &tmp); err != nil {
			return err
		}
		if tmp != nil {
			o.binArray = make([]ign.Binarylizable, 0, len(tmp))
			for _, el0 := range tmp {
				var el ign.Binarylizable = nil
				if el0 != nil {
					var ok bool
					el, ok = el0.(ign.Binarylizable)
					if !ok {
						return fmt.Errorf("failed to convert %v to ign.Binarylizable", el0)
					}
				}
				o.binArray = append(o.binArray, el)
			}
		}
	}
	{
		var tmp []interface{}
		if err := reader.ReadField(ctx, "simpleStructArray", &tmp); err != nil {
			return err
		}
		if tmp != nil {
			o.simpleStructArray = make([]*SimpleStruct, 0, len(tmp))
			for _, el0 := range tmp {
				var el *SimpleStruct = nil
				if el0 != nil {
					var ok bool
					el, ok = el0.(*SimpleStruct)
					if !ok {
						return fmt.Errorf("failed to convert %v to *SimpleStruct", el0)
					}
				}
				o.simpleStructArray = append(o.simpleStructArray, el)
			}
		}
	}
	return nil
}

func (o *Collections) Platform() ign.MarshallerPlatform {
	return ign.JavaMarshaller
}

func (o *Collections) Write(ctx context.Context, writer ign.BinaryWriter) error {
	if err := writer.WriteField(ctx, "list", o.list); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "ignMap", o.ignMap); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "simpleMap", o.simpleMap); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "boMap", o.boMap); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "biMap", o.biMap); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "decMap", o.decMap); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "iMap", o.iMap); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "uuidMap", o.uuidMap); err != nil {
		return err
	}
	return nil
}

func (o *Collections) Read(ctx context.Context, reader ign.BinaryReader) error {
	if err := reader.ReadField(ctx, "list", &o.list); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "ignMap", &o.ignMap); err != nil {
		return err
	}
	{
		var tmp ignite.Map
		if err := reader.ReadField(ctx, "simpleMap", &tmp); err != nil {
			return err
		}
		if !tmp.IsNull() {
			var err error
			o.simpleMap, err = ign.ToMap[string, string](tmp)
			if err != nil {
				return err
			}
		} else {
			o.simpleMap = nil
		}
	}
	{
		var tmp ignite.Map
		if err := reader.ReadField(ctx, "boMap", &tmp); err != nil {
			return err
		}
		if !tmp.IsNull() {
			var err error
			o.boMap, err = ign.ToMap[string, ign.BinaryObject](tmp)
			if err != nil {
				return err
			}
		} else {
			o.boMap = nil
		}
	}
	{
		var tmp ignite.Map
		if err := reader.ReadField(ctx, "biMap", &tmp); err != nil {
			return err
		}
		if !tmp.IsNull() {
			var err error
			o.biMap, err = ign.ToMap[string, ign.Binarylizable](tmp)
			if err != nil {
				return err
			}
		} else {
			o.biMap = nil
		}
	}
	{
		var tmp ignite.Map
		if err := reader.ReadField(ctx, "decMap", &tmp); err != nil {
			return err
		}
		if !tmp.IsNull() {
			var err error
			o.decMap, err = ign.ToMap[apd.Decimal, *SimpleStruct](tmp)
			if err != nil {
				return err
			}
		} else {
			o.decMap = nil
		}
	}
	{
		var tmp ignite.Map
		if err := reader.ReadField(ctx, "iMap", &tmp); err != nil {
			return err
		}
		if !tmp.IsNull() {
			var err error
			o.iMap, err = ign.ToMap[string, interface{}](tmp)
			if err != nil {
				return err
			}
		} else {
			o.iMap = nil
		}
	}
	{
		var tmp ignite.Map
		if err := reader.ReadField(ctx, "uuidMap", &tmp); err != nil {
			return err
		}
		if !tmp.IsNull() {
			var err error
			o.uuidMap, err = ign.ToMap[uuid.UUID, string](tmp)
			if err != nil {
				return err
			}
		} else {
			o.uuidMap = nil
		}
	}
	return nil
}

func (o *SimpleKey) TypeName() string {
	return "KEY"
}

func (o *SimpleKey) Platform() ign.MarshallerPlatform {
	return ign.JavaMarshaller
}

func (o *SimpleKey) Write(ctx context.Context, writer ign.BinaryWriter) error {
	if err := writer.WriteField(ctx, "id", o.id); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "orgId", o.orgId); err != nil {
		return err
	}
	return nil
}

func (o *SimpleKey) AffinityKeyName() string {
	return "orgId"
}

func (o *SimpleKey) Read(ctx context.Context, reader ign.BinaryReader) error {
	{
		var tmp int64
		if err := reader.ReadField(ctx, "id", &tmp); err != nil {
			return err
		}
		o.id = int(tmp)
	}
	{
		var tmp int64
		if err := reader.ReadField(ctx, "orgId", &tmp); err != nil {
			return err
		}
		o.orgId = int(tmp)
	}
	return nil
}

func (o *SimpleStruct) TypeName() string {
	return "VALUE"
}

func (o *SimpleStruct) Platform() ign.MarshallerPlatform {
	return ign.JavaMarshaller
}

func (o *SimpleStruct) Write(ctx context.Context, writer ign.BinaryWriter) error {
	if err := writer.WriteField(ctx, "id", o.id); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "name", o.name); err != nil {
		return err
	}
	return nil
}

func (o *SimpleStruct) Read(ctx context.Context, reader ign.BinaryReader) error {
	{
		var tmp int64
		if err := reader.ReadField(ctx, "id", &tmp); err != nil {
			return err
		}
		o.id = int(tmp)
	}
	if err := reader.ReadField(ctx, "name", &o.name); err != nil {
		return err
	}
	return nil
}

func (o *ComplexKey) TypeName() string {
	return "COMPLEX_KEY"
}

func (o *ComplexKey) Platform() ign.MarshallerPlatform {
	return ign.JavaMarshaller
}

func (o *ComplexKey) Write(ctx context.Context, writer ign.BinaryWriter) error {
	if err := writer.WriteField(ctx, "id", o.id); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "org_id", o.orgId); err != nil {
		return err
	}
	return nil
}

func (o *ComplexKey) AffinityKeyName() string {
	return "org_id"
}

func (o *ComplexKey) Read(ctx context.Context, reader ign.BinaryReader) error {
	{
		var tmp int64
		if err := reader.ReadField(ctx, "id", &tmp); err != nil {
			return err
		}
		o.id = int(tmp)
	}
	{
		var tmp int64
		if err := reader.ReadField(ctx, "org_id", &tmp); err != nil {
			return err
		}
		o.orgId = int(tmp)
	}
	return nil
}

func (o *ComplexStruct) TypeName() string {
	return "COMPLEX_VALUE"
}

func (o *ComplexStruct) Platform() ign.MarshallerPlatform {
	return ign.JavaMarshaller
}

func (o *ComplexStruct) Write(ctx context.Context, writer ign.BinaryWriter) error {
	if err := writer.WriteField(ctx, "name", o.name); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "simple_struct", o.simple); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "binary_object", o.binaryObject); err != nil {
		return err
	}
	return nil
}

func (o *ComplexStruct) Read(ctx context.Context, reader ign.BinaryReader) error {
	if err := reader.ReadField(ctx, "name", &o.name); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "simple_struct", &o.simple); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "binary_object", &o.binaryObject); err != nil {
		return err
	}
	return nil
}

func (o *DotNetStruct) TypeName() string {
	return "DOT_NET_VALUE"
}

func (o *DotNetStruct) Platform() ign.MarshallerPlatform {
	return ign.DotNetMarshaller
}

func (o *DotNetStruct) Write(ctx context.Context, writer ign.BinaryWriter) error {
	if err := writer.WriteField(ctx, "name", o.name); err != nil {
		return err
	}
	return nil
}

func (o *DotNetStruct) Read(ctx context.Context, reader ign.BinaryReader) error {
	if err := reader.ReadField(ctx, "name", &o.name); err != nil {
		return err
	}
	return nil
}

func RegisterCollectionsIgniteTypes(cli *ign.Client) {
	cli.RegisterBinarylizable(func() ign.Binarylizable {
		return &ObjectArrays{}
	})
	cli.RegisterBinarylizable(func() ign.Binarylizable {
		return &Collections{}
	})
	cli.RegisterBinarylizable(func() ign.Binarylizable {
		return &SimpleKey{}
	})
	cli.RegisterBinarylizable(func() ign.Binarylizable {
		return &SimpleStruct{}
	})
	cli.RegisterBinarylizable(func() ign.Binarylizable {
		return &ComplexKey{}
	})
	cli.RegisterBinarylizable(func() ign.Binarylizable {
		return &ComplexStruct{}
	})
	cli.RegisterBinarylizable(func() ign.Binarylizable {
		return &DotNetStruct{}
	})
}
