// go:build testing
package test_binarylizable

// Code generated by gitverse.ru/sbertech/ignite-go-client/tools/generator DO NOT EDIT.

import (
	"gitverse.ru/sbertech/ignite-go-client"
)

func (e SimpleEnum) TypeName() string {
	return "Simple$Enum"
}

func (e SimpleEnum) Platform() ignite.MarshallerPlatform {
	return ignite.JavaMarshaller
}

func (e SimpleEnum) Ordinal() int {
	return int(e)
}

func (e SimpleEnum) Name() string {
	return _SimpleEnum_ord2name[e]
}

func (e SimpleEnum) Values() []ignite.Enum {
	return _SimpleEnum_values
}

const _SimpleEnum_names = "SimpleEnumVal4VAL1VAL2VAL3"

var _SimpleEnum_ord2name = map[SimpleEnum]string{
	SimpleEnumVal4: _SimpleEnum_names[0:14],
	SimpleEnumVal1: _SimpleEnum_names[14:18],
	SimpleEnumVal2: _SimpleEnum_names[18:22],
	SimpleEnumVal3: _SimpleEnum_names[22:26],
}

var _SimpleEnum_values = []ignite.Enum{
	SimpleEnumVal4,
	SimpleEnumVal1,
	SimpleEnumVal2,
	SimpleEnumVal3,
}

func (e Enum) TypeName() string {
	return "ru.gitverse.sbertech.client.filters.TestEnum$Enum"
}

func (e Enum) Platform() ignite.MarshallerPlatform {
	return ignite.JavaMarshaller
}

func (e Enum) Ordinal() int {
	return int(e)
}

func (e Enum) Name() string {
	return _Enum_ord2name[e]
}

func (e Enum) Values() []ignite.Enum {
	return _Enum_values
}

const _Enum_names = "VAL1VAL2VAL3"

var _Enum_ord2name = map[Enum]string{
	EnumVal1: _Enum_names[0:4],
	EnumVal2: _Enum_names[4:8],
	EnumVal3: _Enum_names[8:12],
}

var _Enum_values = []ignite.Enum{
	EnumVal1,
	EnumVal2,
	EnumVal3,
}

func RegisterEnumsIgniteTypes(cli *ignite.Client) error {
	if err := ignite.RegisterEnum[Enum](cli); err != nil {
		return err
	}
	if err := ignite.RegisterEnum[SimpleEnum](cli); err != nil {
		return err
	}
	return nil
}
