// go:build testing
package test_binarylizable

// Code generated by gitverse.ru/sbertech/ignite-go-client/tools/generator DO NOT EDIT.

import (
	"context"

	"gitverse.ru/sbertech/ignite-go-client"
)

func (o *Primitives) Platform() ignite.MarshallerPlatform {
	return ignite.JavaMarshaller
}

func (o *Primitives) Write(ctx context.Context, writer ignite.BinaryWriter) error {
	if err := writer.WriteField(ctx, "fBool", o.fBool); err != nil {
		return err
	}
	if o.pBool == nil {
		if err := writer.WriteNullField(ctx, "pBool", ignite.BoolType); err != nil {
			return err
		}
	} else {
		if err := writer.WriteField(ctx, "pBool", *o.pBool); err != nil {
			return err
		}
	}
	if err := writer.WriteField(ctx, "fByte", o.fByte); err != nil {
		return err
	}
	if o.pByte == nil {
		if err := writer.WriteNullField(ctx, "pByte", ignite.ByteType); err != nil {
			return err
		}
	} else {
		if err := writer.WriteField(ctx, "pByte", *o.pByte); err != nil {
			return err
		}
	}
	if err := writer.WriteField(ctx, "fSByte", o.fSByte); err != nil {
		return err
	}
	if o.pSByte == nil {
		if err := writer.WriteNullField(ctx, "pSByte", ignite.ByteType); err != nil {
			return err
		}
	} else {
		if err := writer.WriteField(ctx, "pSByte", *o.pSByte); err != nil {
			return err
		}
	}
	if err := writer.WriteField(ctx, "fUByte", o.fUByte); err != nil {
		return err
	}
	if o.pUByte == nil {
		if err := writer.WriteNullField(ctx, "pUByte", ignite.ByteType); err != nil {
			return err
		}
	} else {
		if err := writer.WriteField(ctx, "pUByte", *o.pUByte); err != nil {
			return err
		}
	}
	if err := writer.WriteField(ctx, "fShort", o.fShort); err != nil {
		return err
	}
	if o.pShort == nil {
		if err := writer.WriteNullField(ctx, "pShort", ignite.ShortType); err != nil {
			return err
		}
	} else {
		if err := writer.WriteField(ctx, "pShort", *o.pShort); err != nil {
			return err
		}
	}
	if err := writer.WriteField(ctx, "fChar", o.fChar); err != nil {
		return err
	}
	if o.pChar == nil {
		if err := writer.WriteNullField(ctx, "pChar", ignite.CharType); err != nil {
			return err
		}
	} else {
		if err := writer.WriteField(ctx, "pChar", *o.pChar); err != nil {
			return err
		}
	}
	if err := writer.WriteField(ctx, "fInt32", o.fInt32); err != nil {
		return err
	}
	if o.pInt32 == nil {
		if err := writer.WriteNullField(ctx, "pInt32", ignite.IntType); err != nil {
			return err
		}
	} else {
		if err := writer.WriteField(ctx, "pInt32", *o.pInt32); err != nil {
			return err
		}
	}
	if err := writer.WriteField(ctx, "fUint32", o.fUint32); err != nil {
		return err
	}
	if o.pUint32 == nil {
		if err := writer.WriteNullField(ctx, "pUint32", ignite.IntType); err != nil {
			return err
		}
	} else {
		if err := writer.WriteField(ctx, "pUint32", *o.pUint32); err != nil {
			return err
		}
	}
	if err := writer.WriteField(ctx, "fInt64", o.fInt64); err != nil {
		return err
	}
	if o.pInt64 == nil {
		if err := writer.WriteNullField(ctx, "pInt64", ignite.LongType); err != nil {
			return err
		}
	} else {
		if err := writer.WriteField(ctx, "pInt64", *o.pInt64); err != nil {
			return err
		}
	}
	if err := writer.WriteField(ctx, "fUint64", o.fUint64); err != nil {
		return err
	}
	if o.pUint64 == nil {
		if err := writer.WriteNullField(ctx, "pUint64", ignite.LongType); err != nil {
			return err
		}
	} else {
		if err := writer.WriteField(ctx, "pUint64", *o.pUint64); err != nil {
			return err
		}
	}
	if err := writer.WriteField(ctx, "fInt", o.fInt); err != nil {
		return err
	}
	if o.pInt == nil {
		if err := writer.WriteNullField(ctx, "pInt", ignite.LongType); err != nil {
			return err
		}
	} else {
		if err := writer.WriteField(ctx, "pInt", *o.pInt); err != nil {
			return err
		}
	}
	if err := writer.WriteField(ctx, "fUint", o.fUint); err != nil {
		return err
	}
	if o.pUint == nil {
		if err := writer.WriteNullField(ctx, "pUint", ignite.LongType); err != nil {
			return err
		}
	} else {
		if err := writer.WriteField(ctx, "pUint", *o.pUint); err != nil {
			return err
		}
	}
	if err := writer.WriteField(ctx, "fFloat32", o.fFloat32); err != nil {
		return err
	}
	if o.pFloat32 == nil {
		if err := writer.WriteNullField(ctx, "pFloat32", ignite.FloatType); err != nil {
			return err
		}
	} else {
		if err := writer.WriteField(ctx, "pFloat32", *o.pFloat32); err != nil {
			return err
		}
	}
	if err := writer.WriteField(ctx, "fFloat64", o.fFloat64); err != nil {
		return err
	}
	if o.pFloat64 == nil {
		if err := writer.WriteNullField(ctx, "pFloat64", ignite.DoubleType); err != nil {
			return err
		}
	} else {
		if err := writer.WriteField(ctx, "pFloat64", *o.pFloat64); err != nil {
			return err
		}
	}
	return nil
}

func (o *Primitives) Read(ctx context.Context, reader ignite.BinaryReader) error {
	if err := reader.ReadField(ctx, "fBool", &o.fBool); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "pBool", &o.pBool); err != nil {
		return err
	}
	{
		var tmp int8
		if err := reader.ReadField(ctx, "fByte", &tmp); err != nil {
			return err
		}
		o.fByte = byte(tmp)
	}
	{
		var tmp *int8
		if err := reader.ReadField(ctx, "pByte", &tmp); err != nil {
			return err
		}
		if tmp != nil {
			tmp0 := byte(*tmp)
			o.pByte = &tmp0
		} else {
			o.pByte = nil
		}
	}
	if err := reader.ReadField(ctx, "fSByte", &o.fSByte); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "pSByte", &o.pSByte); err != nil {
		return err
	}
	{
		var tmp int8
		if err := reader.ReadField(ctx, "fUByte", &tmp); err != nil {
			return err
		}
		o.fUByte = uint8(tmp)
	}
	{
		var tmp *int8
		if err := reader.ReadField(ctx, "pUByte", &tmp); err != nil {
			return err
		}
		if tmp != nil {
			tmp0 := uint8(*tmp)
			o.pUByte = &tmp0
		} else {
			o.pUByte = nil
		}
	}
	if err := reader.ReadField(ctx, "fShort", &o.fShort); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "pShort", &o.pShort); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "fChar", &o.fChar); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "pChar", &o.pChar); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "fInt32", &o.fInt32); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "pInt32", &o.pInt32); err != nil {
		return err
	}
	{
		var tmp int32
		if err := reader.ReadField(ctx, "fUint32", &tmp); err != nil {
			return err
		}
		o.fUint32 = uint32(tmp)
	}
	{
		var tmp *int32
		if err := reader.ReadField(ctx, "pUint32", &tmp); err != nil {
			return err
		}
		if tmp != nil {
			tmp0 := uint32(*tmp)
			o.pUint32 = &tmp0
		} else {
			o.pUint32 = nil
		}
	}
	if err := reader.ReadField(ctx, "fInt64", &o.fInt64); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "pInt64", &o.pInt64); err != nil {
		return err
	}
	{
		var tmp int64
		if err := reader.ReadField(ctx, "fUint64", &tmp); err != nil {
			return err
		}
		o.fUint64 = uint64(tmp)
	}
	{
		var tmp *int64
		if err := reader.ReadField(ctx, "pUint64", &tmp); err != nil {
			return err
		}
		if tmp != nil {
			tmp0 := uint64(*tmp)
			o.pUint64 = &tmp0
		} else {
			o.pUint64 = nil
		}
	}
	{
		var tmp int64
		if err := reader.ReadField(ctx, "fInt", &tmp); err != nil {
			return err
		}
		o.fInt = int(tmp)
	}
	{
		var tmp *int64
		if err := reader.ReadField(ctx, "pInt", &tmp); err != nil {
			return err
		}
		if tmp != nil {
			tmp0 := int(*tmp)
			o.pInt = &tmp0
		} else {
			o.pInt = nil
		}
	}
	{
		var tmp int64
		if err := reader.ReadField(ctx, "fUint", &tmp); err != nil {
			return err
		}
		o.fUint = uint(tmp)
	}
	{
		var tmp *int64
		if err := reader.ReadField(ctx, "pUint", &tmp); err != nil {
			return err
		}
		if tmp != nil {
			tmp0 := uint(*tmp)
			o.pUint = &tmp0
		} else {
			o.pUint = nil
		}
	}
	if err := reader.ReadField(ctx, "fFloat32", &o.fFloat32); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "pFloat32", &o.pFloat32); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "fFloat64", &o.fFloat64); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "pFloat64", &o.pFloat64); err != nil {
		return err
	}
	return nil
}

func RegisterPrimitives(cli *ignite.Client) {
	cli.RegisterBinarylizable(func() ignite.Binarylizable {
		return &Primitives{}
	})
}
