// go:build testing
package test_binarylizable

// Code generated by gitverse.ru/sbertech/ignite-go-client/tools/generator DO NOT EDIT.

import (
	"context"

	"gitverse.ru/sbertech/ignite-go-client"
)

func (o *PrimitiveArrays) Platform() ignite.MarshallerPlatform {
	return ignite.JavaMarshaller
}

func (o *PrimitiveArrays) Write(ctx context.Context, writer ignite.BinaryWriter) error {
	if err := writer.WriteField(ctx, "boolArray", o.boolArray); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "byteArray", o.byteArray); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "sByteArray", o.sByteArray); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "uByteArray", o.uByteArray); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "shortArray", o.shortArray); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "charArray", o.charArray); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "int32Array", o.int32Array); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "uint32Array", o.uint32Array); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "int64Array", o.int64Array); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "uint64Array", o.uint64Array); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "intArray", o.intArray); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "uintArray", o.uintArray); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "float32Array", o.float32Array); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "float64Array", o.float64Array); err != nil {
		return err
	}
	return nil
}

func (o *PrimitiveArrays) Read(ctx context.Context, reader ignite.BinaryReader) error {
	if err := reader.ReadField(ctx, "boolArray", &o.boolArray); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "byteArray", &o.byteArray); err != nil {
		return err
	}
	{
		var tmp []byte
		if err := reader.ReadField(ctx, "sByteArray", &tmp); err != nil {
			return err
		}
		if tmp != nil {
			o.sByteArray = make([]int8, 0, len(tmp))
			for _, el := range tmp {
				o.sByteArray = append(o.sByteArray, int8(el))

			}
		} else {
			o.sByteArray = nil
		}
	}
	if err := reader.ReadField(ctx, "uByteArray", &o.uByteArray); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "shortArray", &o.shortArray); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "charArray", &o.charArray); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "int32Array", &o.int32Array); err != nil {
		return err
	}
	{
		var tmp []int32
		if err := reader.ReadField(ctx, "uint32Array", &tmp); err != nil {
			return err
		}
		if tmp != nil {
			o.uint32Array = make([]uint32, 0, len(tmp))
			for _, el := range tmp {
				o.uint32Array = append(o.uint32Array, uint32(el))

			}
		} else {
			o.uint32Array = nil
		}
	}
	if err := reader.ReadField(ctx, "int64Array", &o.int64Array); err != nil {
		return err
	}
	{
		var tmp []int64
		if err := reader.ReadField(ctx, "uint64Array", &tmp); err != nil {
			return err
		}
		if tmp != nil {
			o.uint64Array = make([]uint64, 0, len(tmp))
			for _, el := range tmp {
				o.uint64Array = append(o.uint64Array, uint64(el))

			}
		} else {
			o.uint64Array = nil
		}
	}
	{
		var tmp []int64
		if err := reader.ReadField(ctx, "intArray", &tmp); err != nil {
			return err
		}
		if tmp != nil {
			o.intArray = make([]int, 0, len(tmp))
			for _, el := range tmp {
				o.intArray = append(o.intArray, int(el))

			}
		} else {
			o.intArray = nil
		}
	}
	{
		var tmp []int64
		if err := reader.ReadField(ctx, "uintArray", &tmp); err != nil {
			return err
		}
		if tmp != nil {
			o.uintArray = make([]uint, 0, len(tmp))
			for _, el := range tmp {
				o.uintArray = append(o.uintArray, uint(el))

			}
		} else {
			o.uintArray = nil
		}
	}
	if err := reader.ReadField(ctx, "float32Array", &o.float32Array); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "float64Array", &o.float64Array); err != nil {
		return err
	}
	return nil
}

func RegisterPrimitiveArrays(cli *ignite.Client) {
	cli.RegisterBinarylizable(func() ignite.Binarylizable {
		return &PrimitiveArrays{}
	})
}
