// go:build testing
package test_binarylizable

// Code generated by gitverse.ru/sbertech/ignite-go-client/tools/generator DO NOT EDIT.

import (
	"context"
	t "time"

	dec "github.com/cockroachdb/apd/v3"
	uid "github.com/google/uuid"
	ign "gitverse.ru/sbertech/ignite-go-client"
)

func (o *Specials) Platform() ign.MarshallerPlatform {
	return ign.JavaMarshaller
}

func (o *Specials) Write(ctx context.Context, writer ign.BinaryWriter) error {
	if err := writer.WriteField(ctx, "fString", o.fString); err != nil {
		return err
	}
	if o.pString == nil {
		if err := writer.WriteNullField(ctx, "pString", ign.StringType); err != nil {
			return err
		}
	} else {
		if err := writer.WriteField(ctx, "pString", *o.pString); err != nil {
			return err
		}
	}
	if err := writer.WriteField(ctx, "fUuid", o.fUuid); err != nil {
		return err
	}
	if o.pUuid == nil {
		if err := writer.WriteNullField(ctx, "pUuid", ign.UuidType); err != nil {
			return err
		}
	} else {
		if err := writer.WriteField(ctx, "pUuid", *o.pUuid); err != nil {
			return err
		}
	}
	if err := writer.WriteField(ctx, "fDate", o.fDate); err != nil {
		return err
	}
	if o.pDate == nil {
		if err := writer.WriteNullField(ctx, "pDate", ign.DateType); err != nil {
			return err
		}
	} else {
		if err := writer.WriteField(ctx, "pDate", *o.pDate); err != nil {
			return err
		}
	}
	if err := writer.WriteField(ctx, "fTime", o.fTime); err != nil {
		return err
	}
	if o.pTime == nil {
		if err := writer.WriteNullField(ctx, "pTime", ign.TimeType); err != nil {
			return err
		}
	} else {
		if err := writer.WriteField(ctx, "pTime", *o.pTime); err != nil {
			return err
		}
	}
	if err := writer.WriteField(ctx, "fTimestamp", o.fTimestamp); err != nil {
		return err
	}
	if o.pTimestamp == nil {
		if err := writer.WriteNullField(ctx, "pTimestamp", ign.TimestampType); err != nil {
			return err
		}
	} else {
		if err := writer.WriteField(ctx, "pTimestamp", *o.pTimestamp); err != nil {
			return err
		}
	}
	if err := writer.WriteField(ctx, "fDecimal", o.fDecimal); err != nil {
		return err
	}
	if o.pDecimal == nil {
		if err := writer.WriteNullField(ctx, "pDecimal", ign.DecimalType); err != nil {
			return err
		}
	} else {
		if err := writer.WriteField(ctx, "pDecimal", o.pDecimal); err != nil {
			return err
		}
	}
	return nil
}

func (o *Specials) Read(ctx context.Context, reader ign.BinaryReader) error {
	if err := reader.ReadField(ctx, "fString", &o.fString); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "pString", &o.pString); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "fUuid", &o.fUuid); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "pUuid", &o.pUuid); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "fDate", &o.fDate); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "pDate", &o.pDate); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "fTime", &o.fTime); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "pTime", &o.pTime); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "fTimestamp", &o.fTimestamp); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "pTimestamp", &o.pTimestamp); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "fDecimal", &o.fDecimal); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "pDecimal", &o.pDecimal); err != nil {
		return err
	}
	return nil
}

func (o *SpecialArrays) Platform() ign.MarshallerPlatform {
	return ign.JavaMarshaller
}

func (o *SpecialArrays) Write(ctx context.Context, writer ign.BinaryWriter) error {
	if err := writer.WriteField(ctx, "stringArray", o.stringArray); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "stringPArray", o.stringPArray); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "uuidArray", o.uuidArray); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "uuidPArray", o.uuidPArray); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "dateArray", o.dateArray); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "datePArray", o.datePArray); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "timeArray", o.timeArray); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "timePArray", o.timePArray); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "timeStampArray", o.timeStampArray); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "timeStampPArray", o.timeStampPArray); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "decimalArray", o.decimalArray); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "decimalPArray", o.decimalPArray); err != nil {
		return err
	}
	return nil
}

func (o *SpecialArrays) Read(ctx context.Context, reader ign.BinaryReader) error {
	{
		var tmp []*string
		if err := reader.ReadField(ctx, "stringArray", &tmp); err != nil {
			return err
		}
		if tmp != nil {
			o.stringArray = make([]string, 0, len(tmp))
			for _, pel := range tmp {
				var el string
				if pel != nil {
					el = *pel
				}
				o.stringArray = append(o.stringArray, el)
			}
		}
	}
	if err := reader.ReadField(ctx, "stringPArray", &o.stringPArray); err != nil {
		return err
	}
	{
		var tmp []*uid.UUID
		if err := reader.ReadField(ctx, "uuidArray", &tmp); err != nil {
			return err
		}
		if tmp != nil {
			o.uuidArray = make([]uid.UUID, 0, len(tmp))
			for _, pel := range tmp {
				var el uid.UUID
				if pel != nil {
					el = *pel
				}
				o.uuidArray = append(o.uuidArray, el)
			}
		}
	}
	if err := reader.ReadField(ctx, "uuidPArray", &o.uuidPArray); err != nil {
		return err
	}
	{
		var tmp []*ign.Date
		if err := reader.ReadField(ctx, "dateArray", &tmp); err != nil {
			return err
		}
		if tmp != nil {
			o.dateArray = make([]ign.Date, 0, len(tmp))
			for _, pel := range tmp {
				var el ign.Date
				if pel != nil {
					el = *pel
				}
				o.dateArray = append(o.dateArray, el)
			}
		}
	}
	if err := reader.ReadField(ctx, "datePArray", &o.datePArray); err != nil {
		return err
	}
	{
		var tmp []*ign.Time
		if err := reader.ReadField(ctx, "timeArray", &tmp); err != nil {
			return err
		}
		if tmp != nil {
			o.timeArray = make([]ign.Time, 0, len(tmp))
			for _, pel := range tmp {
				var el ign.Time
				if pel != nil {
					el = *pel
				}
				o.timeArray = append(o.timeArray, el)
			}
		}
	}
	if err := reader.ReadField(ctx, "timePArray", &o.timePArray); err != nil {
		return err
	}
	{
		var tmp []*t.Time
		if err := reader.ReadField(ctx, "timeStampArray", &tmp); err != nil {
			return err
		}
		if tmp != nil {
			o.timeStampArray = make([]t.Time, 0, len(tmp))
			for _, pel := range tmp {
				var el t.Time
				if pel != nil {
					el = *pel
				}
				o.timeStampArray = append(o.timeStampArray, el)
			}
		}
	}
	if err := reader.ReadField(ctx, "timeStampPArray", &o.timeStampPArray); err != nil {
		return err
	}
	{
		var tmp []*dec.Decimal
		if err := reader.ReadField(ctx, "decimalArray", &tmp); err != nil {
			return err
		}
		if tmp != nil {
			o.decimalArray = make([]dec.Decimal, 0, len(tmp))
			for _, pel := range tmp {
				var el dec.Decimal
				if pel != nil {
					el = *pel
				}
				o.decimalArray = append(o.decimalArray, el)
			}
		}
	}
	if err := reader.ReadField(ctx, "decimalPArray", &o.decimalPArray); err != nil {
		return err
	}
	return nil
}

func RegisterSpecialsIgniteTypes(cli *ign.Client) error {
	if err := ign.RegisterType[*Specials](cli); err != nil {
		return err
	}
	if err := ign.RegisterType[*SpecialArrays](cli); err != nil {
		return err
	}
	return nil
}
