// go:build testing
package test_binarylizable

// Code generated by gitverse.ru/sbertech/ignite-go-client/tools/generator DO NOT EDIT.

import (
	"context"

	"gitverse.ru/sbertech/ignite-go-client"
)

func (o *TestEnum) TypeName() string {
	return "ru.gitverse.sbertech.client.filters.TestEnum"
}

func (o *TestEnum) Platform() ignite.MarshallerPlatform {
	return ignite.JavaMarshaller
}

func (o *TestEnum) Write(ctx context.Context, writer ignite.BinaryWriter) error {
	if err := writer.WriteField(ctx, "id", o.id); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "enumField", o.enumField); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "enumArrayField", o.enumArrayField); err != nil {
		return err
	}
	return nil
}

func (o *TestEnum) Read(ctx context.Context, reader ignite.BinaryReader) error {
	{
		var tmp int64
		if err := reader.ReadField(ctx, "id", &tmp); err != nil {
			return err
		}
		o.id = int(tmp)
	}
	if err := reader.ReadField(ctx, "enumField", &o.enumField); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "enumArrayField", &o.enumArrayField); err != nil {
		return err
	}
	return nil
}

func (e Enum1) Platform() ignite.MarshallerPlatform {
	return ignite.JavaMarshaller
}

func (e Enum1) Ordinal() int {
	return int(e)
}

func (e Enum1) Name() string {
	return _Enum1_ord2name[e]
}

func (e Enum1) Values() []ignite.Enum {
	return _Enum1_values
}

const _Enum1_names = "VAL1VAL2VAL3"

var _Enum1_ord2name = map[Enum1]string{
	Enum1Val1: _Enum1_names[0:4],
	Enum2Val2: _Enum1_names[4:8],
	Enum3Val3: _Enum1_names[8:12],
}

var _Enum1_values = []ignite.Enum{
	Enum1Val1,
	Enum2Val2,
	Enum3Val3,
}

func RegisterTestEnumsIgniteTypes(cli *ignite.Client) error {
	if err := ignite.RegisterType[*TestEnum](cli); err != nil {
		return err
	}
	if err := ignite.RegisterEnum[Enum1](cli); err != nil {
		return err
	}
	return nil
}
