// Code generated by "stringer -tags=testing -type=Rank"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Private-0]
	_ = x[Lieutenant-1]
}

const _Rank_name = "PrivateLieutenant"

var _Rank_index = [...]uint8{0, 7, 17}

func (i Rank) String() string {
	if i < 0 || i >= Rank(len(_Rank_index)-1) {
		return "Rank(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Rank_name[_Rank_index[i]:_Rank_index[i+1]]
}
