// go:build testing
package main

// Code generated by gitverse.ru/sbertech/ignite-go-client/tools/generator DO NOT EDIT.

import (
	"gitverse.ru/sbertech/ignite-go-client"
)

func (e Rank) TypeName() string {
	return "RANK"
}

func (e Rank) Platform() ignite.MarshallerPlatform {
	return ignite.JavaMarshaller
}

func (e Rank) Ordinal() int {
	return int(e)
}

func (e Rank) Name() string {
	return _Rank_ord2name[e]
}

func (e Rank) Values() []ignite.Enum {
	return _Rank_values
}

const _Rank_names = "LIEUTENANTPRIVATE"

var _Rank_ord2name = map[Rank]string{
	Lieutenant: _Rank_names[0:10],
	Private:    _Rank_names[10:17],
}

var _Rank_values = []ignite.Enum{
	Lieutenant,
	Private,
}

func RegisterRank(cli *ignite.Client) error {
	if err := ignite.RegisterEnum[Rank](cli); err != nil {
		return err
	}
	return nil
}
