// go:build testing
package main

// Code generated by gitverse.ru/sbertech/ignite-go-client/tools/generator DO NOT EDIT.

import (
	"context"

	"gitverse.ru/sbertech/ignite-go-client"
)

func (o *PersonKey) TypeName() string {
	return "SQL_PERSON_KEY"
}

func (o *PersonKey) Platform() ignite.MarshallerPlatform {
	return ignite.JavaMarshaller
}

func (o *PersonKey) Write(ctx context.Context, writer ignite.BinaryWriter) error {
	if err := writer.WriteField(ctx, "id", o.id); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "company", o.company); err != nil {
		return err
	}
	return nil
}

func (o *PersonKey) Read(ctx context.Context, reader ignite.BinaryReader) error {
	if err := reader.ReadField(ctx, "id", &o.id); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "company", &o.company); err != nil {
		return err
	}
	return nil
}

func (o *Person) TypeName() string {
	return "SQL_PERSON"
}

func (o *Person) Platform() ignite.MarshallerPlatform {
	return ignite.JavaMarshaller
}

func (o *Person) Write(ctx context.Context, writer ignite.BinaryWriter) error {
	if err := writer.WriteField(ctx, "name", o.name); err != nil {
		return err
	}
	if err := writer.WriteField(ctx, "age", o.age); err != nil {
		return err
	}
	return nil
}

func (o *Person) Read(ctx context.Context, reader ignite.BinaryReader) error {
	if err := reader.ReadField(ctx, "name", &o.name); err != nil {
		return err
	}
	if err := reader.ReadField(ctx, "age", &o.age); err != nil {
		return err
	}
	return nil
}

func RegisterMainIgniteTypes(cli *ignite.Client) error {
	if err := ignite.RegisterType[*PersonKey](cli); err != nil {
		return err
	}
	if err := ignite.RegisterType[*Person](cli); err != nil {
		return err
	}
	return nil
}
