// Code generated by "gen_req_resp.go"; DO NOT EDIT.
package serdes

type Field struct {
	Name         *string
	IsDescensing bool
}

type QueryIndex struct {
	Name       *string
	Type       byte
	InlineSize int32
	Fields     []Field
}

type QueryField struct {
	Name      *string
	TypeName  *string
	IsKey     bool
	IsNotNull bool
}

type QueryEntity struct {
	KeyTypeName    *string
	ValueTypeName  *string
	TableName      *string
	KeyFieldName   *string
	ValueFieldName *string
	QueryFields    []QueryField
	Aliases        *map[string]string
	QueryIndex     []QueryIndex
}

type CacheKeyConfiguration struct {
	TypeName             *string
	AffinityKeyFieldName *string
}

type CacheConfiguration struct {
	Length                        int32
	AtomicityMode                 int32
	Backups                       int32
	CacheMode                     int32
	CopyOnRead                    bool
	DataRegionName                *string
	EagerTTL                      bool
	StatisticsEnabled             bool
	GroupName                     *string
	DefaultLockTimeout            int64
	MaxConcurrentAsyncOperations  int32
	MaxQueryIterators             int32
	Name                          *string
	IsOnheapCacheEnabled          bool
	PartitionLossPolicy           int32
	QueryDetailMetricsSize        int32
	QueryParellelism              int32
	ReadFromBackup                bool
	RebalanceBatchSize            int32
	RebalanceBatchesPrefetchCount int64
	RebalanceDelay                int64
	RebalanceMode                 int32
	RebalanceOrder                int32
	RebalanceThrottle             int64
	RebalanceTimeout              int64
	SqlEscapeAll                  bool
	SqlIndexInlineMaxSize         int32
	SqlSchema                     *string
	WriteSynchronizationMode      int32
	CacheKeyConfigurations        []CacheKeyConfiguration
	QueryEntities                 []QueryEntity
}

func (req Field) Write(buf *IgniteBuffer) {
	buf.WriteString(req.Name)
	buf.WriteBool(req.IsDescensing)
}

func (buf *IgniteBuffer) ReadField() Field {
	resp := Field{}
	resp.Name = buf.ReadString()
	resp.IsDescensing = buf.ReadBool()
	return resp
}

func (req QueryIndex) Write(buf *IgniteBuffer) {
	buf.WriteString(req.Name)
	buf.WriteByte(req.Type)
	buf.WriteInt32(req.InlineSize)
	buf.WriteFieldArrayWithoutType(req.Fields)
}

func (buf *IgniteBuffer) ReadQueryIndex() QueryIndex {
	resp := QueryIndex{}
	resp.Name = buf.ReadString()
	resp.Type = buf.ReadByte()
	resp.InlineSize = buf.ReadInt32()
	resp.Fields = buf.ReadFieldArrayWithoutType()
	return resp
}

func (req QueryField) Write(buf *IgniteBuffer) {
	buf.WriteString(req.Name)
	buf.WriteString(req.TypeName)
	buf.WriteBool(req.IsKey)
	buf.WriteBool(req.IsNotNull)
}

func (buf *IgniteBuffer) ReadQueryField() QueryField {
	resp := QueryField{}
	resp.Name = buf.ReadString()
	resp.TypeName = buf.ReadString()
	resp.IsKey = buf.ReadBool()
	resp.IsNotNull = buf.ReadBool()
	return resp
}

func (req QueryEntity) Write(buf *IgniteBuffer) {
	buf.WriteString(req.KeyTypeName)
	buf.WriteString(req.ValueTypeName)
	buf.WriteString(req.TableName)
	buf.WriteString(req.KeyFieldName)
	buf.WriteString(req.ValueFieldName)
	buf.WriteQueryFieldArrayWithoutType(req.QueryFields)
	buf.WriteStringStringWithoutType(req.Aliases)
	buf.WriteQueryIndexArrayWithoutType(req.QueryIndex)
}

func (buf *IgniteBuffer) ReadQueryEntity() QueryEntity {
	resp := QueryEntity{}
	resp.KeyTypeName = buf.ReadString()
	resp.ValueTypeName = buf.ReadString()
	resp.TableName = buf.ReadString()
	resp.KeyFieldName = buf.ReadString()
	resp.ValueFieldName = buf.ReadString()
	resp.QueryFields = buf.ReadQueryFieldArrayWithoutType()
	resp.Aliases = buf.ReadStringStringWithoutType()
	resp.QueryIndex = buf.ReadQueryIndexArrayWithoutType()
	return resp
}

func (req CacheKeyConfiguration) Write(buf *IgniteBuffer) {
	buf.WriteString(req.TypeName)
	buf.WriteString(req.AffinityKeyFieldName)
}

func (buf *IgniteBuffer) ReadCacheKeyConfiguration() CacheKeyConfiguration {
	resp := CacheKeyConfiguration{}
	resp.TypeName = buf.ReadString()
	resp.AffinityKeyFieldName = buf.ReadString()
	return resp
}

func (req CacheConfiguration) Write(buf *IgniteBuffer) {
	buf.WriteInt32(req.Length)
	buf.WriteInt32(req.AtomicityMode)
	buf.WriteInt32(req.Backups)
	buf.WriteInt32(req.CacheMode)
	buf.WriteBool(req.CopyOnRead)
	buf.WriteString(req.DataRegionName)
	buf.WriteBool(req.EagerTTL)
	buf.WriteBool(req.StatisticsEnabled)
	buf.WriteString(req.GroupName)
	buf.WriteInt64(req.DefaultLockTimeout)
	buf.WriteInt32(req.MaxConcurrentAsyncOperations)
	buf.WriteInt32(req.MaxQueryIterators)
	buf.WriteString(req.Name)
	buf.WriteBool(req.IsOnheapCacheEnabled)
	buf.WriteInt32(req.PartitionLossPolicy)
	buf.WriteInt32(req.QueryDetailMetricsSize)
	buf.WriteInt32(req.QueryParellelism)
	buf.WriteBool(req.ReadFromBackup)
	buf.WriteInt32(req.RebalanceBatchSize)
	buf.WriteInt64(req.RebalanceBatchesPrefetchCount)
	buf.WriteInt64(req.RebalanceDelay)
	buf.WriteInt32(req.RebalanceMode)
	buf.WriteInt32(req.RebalanceOrder)
	buf.WriteInt64(req.RebalanceThrottle)
	buf.WriteInt64(req.RebalanceTimeout)
	buf.WriteBool(req.SqlEscapeAll)
	buf.WriteInt32(req.SqlIndexInlineMaxSize)
	buf.WriteString(req.SqlSchema)
	buf.WriteInt32(req.WriteSynchronizationMode)
	buf.WriteCacheKeyConfigurationArrayWithoutType(req.CacheKeyConfigurations)
	buf.WriteQueryEntityArrayWithoutType(req.QueryEntities)
}

func (buf *IgniteBuffer) ReadCacheConfiguration() CacheConfiguration {
	resp := CacheConfiguration{}
	resp.Length = buf.ReadInt32()
	resp.AtomicityMode = buf.ReadInt32()
	resp.Backups = buf.ReadInt32()
	resp.CacheMode = buf.ReadInt32()
	resp.CopyOnRead = buf.ReadBool()
	resp.DataRegionName = buf.ReadString()
	resp.EagerTTL = buf.ReadBool()
	resp.StatisticsEnabled = buf.ReadBool()
	resp.GroupName = buf.ReadString()
	resp.DefaultLockTimeout = buf.ReadInt64()
	resp.MaxConcurrentAsyncOperations = buf.ReadInt32()
	resp.MaxQueryIterators = buf.ReadInt32()
	resp.Name = buf.ReadString()
	resp.IsOnheapCacheEnabled = buf.ReadBool()
	resp.PartitionLossPolicy = buf.ReadInt32()
	resp.QueryDetailMetricsSize = buf.ReadInt32()
	resp.QueryParellelism = buf.ReadInt32()
	resp.ReadFromBackup = buf.ReadBool()
	resp.RebalanceBatchSize = buf.ReadInt32()
	resp.RebalanceBatchesPrefetchCount = buf.ReadInt64()
	resp.RebalanceDelay = buf.ReadInt64()
	resp.RebalanceMode = buf.ReadInt32()
	resp.RebalanceOrder = buf.ReadInt32()
	resp.RebalanceThrottle = buf.ReadInt64()
	resp.RebalanceTimeout = buf.ReadInt64()
	resp.SqlEscapeAll = buf.ReadBool()
	resp.SqlIndexInlineMaxSize = buf.ReadInt32()
	resp.SqlSchema = buf.ReadString()
	resp.WriteSynchronizationMode = buf.ReadInt32()
	resp.CacheKeyConfigurations = buf.ReadCacheKeyConfigurationArrayWithoutType()
	resp.QueryEntities = buf.ReadQueryEntityArrayWithoutType()
	return resp
}

func (buf *IgniteBuffer) WriteCacheKeyConfigurationArrayWithoutType(req []CacheKeyConfiguration) {
	l := len(req)
	buf.WriteInt32(int32(l))
	for i := 0; i < l; i++ {
		req[i].Write(buf)
	}
}

func (buf *IgniteBuffer) ReadCacheKeyConfigurationArrayWithoutType() []CacheKeyConfiguration {
	l := int(buf.ReadInt32())
	res := make([]CacheKeyConfiguration, l)
	for i := 0; i < l; i++ {
		res[i] = buf.ReadCacheKeyConfiguration()
	}
	return res
}

func (buf *IgniteBuffer) WriteFieldArrayWithoutType(req []Field) {
	l := len(req)
	buf.WriteInt32(int32(l))
	for i := 0; i < l; i++ {
		req[i].Write(buf)
	}
}

func (buf *IgniteBuffer) ReadFieldArrayWithoutType() []Field {
	l := int(buf.ReadInt32())
	res := make([]Field, l)
	for i := 0; i < l; i++ {
		res[i] = buf.ReadField()
	}
	return res
}

func (buf *IgniteBuffer) WriteQueryEntityArrayWithoutType(req []QueryEntity) {
	l := len(req)
	buf.WriteInt32(int32(l))
	for i := 0; i < l; i++ {
		req[i].Write(buf)
	}
}

func (buf *IgniteBuffer) ReadQueryEntityArrayWithoutType() []QueryEntity {
	l := int(buf.ReadInt32())
	res := make([]QueryEntity, l)
	for i := 0; i < l; i++ {
		res[i] = buf.ReadQueryEntity()
	}
	return res
}

func (buf *IgniteBuffer) WriteQueryFieldArrayWithoutType(req []QueryField) {
	l := len(req)
	buf.WriteInt32(int32(l))
	for i := 0; i < l; i++ {
		req[i].Write(buf)
	}
}

func (buf *IgniteBuffer) ReadQueryFieldArrayWithoutType() []QueryField {
	l := int(buf.ReadInt32())
	res := make([]QueryField, l)
	for i := 0; i < l; i++ {
		res[i] = buf.ReadQueryField()
	}
	return res
}

func (buf *IgniteBuffer) WriteQueryIndexArrayWithoutType(req []QueryIndex) {
	l := len(req)
	buf.WriteInt32(int32(l))
	for i := 0; i < l; i++ {
		req[i].Write(buf)
	}
}

func (buf *IgniteBuffer) ReadQueryIndexArrayWithoutType() []QueryIndex {
	l := int(buf.ReadInt32())
	res := make([]QueryIndex, l)
	for i := 0; i < l; i++ {
		res[i] = buf.ReadQueryIndex()
	}
	return res
}
