// Code generated by "gen_req_resp.go"; DO NOT EDIT.
package serdes

type CacheDestroyRequest struct {
	CacheId int32
}

type CacheDestroyResponse struct {
}

func (req CacheDestroyRequest) OpCode() int16 {
	return 1056
}

func (req CacheDestroyRequest) Write(buf *IgniteBuffer) {
	buf.WriteInt32(req.CacheId)
}

func (req CacheDestroyRequest) ReadResponse(buf *IgniteBuffer) interface{} {
	resp := CacheDestroyResponse{}
	return resp
}
