// Code generated by "gen_req_resp.go"; DO NOT EDIT.
package serdes

type CacheGetNamesRequest struct {
}

type CacheGetNamesResponse struct {
	Caches *[]string
}

func (req CacheGetNamesRequest) OpCode() int16 {
	return 1050
}

func CreateCacheGetNamesRequest() CacheGetNamesRequest {
	return CacheGetNamesRequest{}
}

func (req CacheGetNamesRequest) Write(buf *IgniteBuffer) {
}

func (req CacheGetNamesRequest) ReadResponse(buf *IgniteBuffer) interface{} {
	resp := CacheGetNamesResponse{}
	resp.Caches = buf.ReadStringArrayWithoutType()
	return resp
}
