// Code generated by "gen_req_resp.go"; DO NOT EDIT.
package serdes

type CacheCreateWithNameRequest struct {
	Cache *string
}

type CacheCreateWithNameResponse struct {
}

func (req CacheCreateWithNameRequest) OpCode() int16 {
	return 1051
}

func CreateCacheCreateWithNameRequest() CacheCreateWithNameRequest {
	return CacheCreateWithNameRequest{}
}

func (req CacheCreateWithNameRequest) Write(buf *IgniteBuffer) {
	buf.WriteString(req.Cache)
}

func (req CacheCreateWithNameRequest) ReadResponse(buf *IgniteBuffer) interface{} {
	resp := CacheCreateWithNameResponse{}
	return resp
}
