// Code generated by "gen_req_resp.go"; DO NOT EDIT.
package serdes

type CacheCreateWithConfigurationRequest struct {
	Config CacheConfiguration
}

type CacheCreateWithConfigurationResponse struct {
}

func (req CacheCreateWithConfigurationRequest) OpCode() int16 {
	return 1053
}

func (req CacheCreateWithConfigurationRequest) Write(buf *IgniteBuffer) {
	buf.WriteCacheConfiguration(req.Config)
}

func (req CacheCreateWithConfigurationRequest) ReadResponse(buf *IgniteBuffer) interface{} {
	resp := CacheCreateWithConfigurationResponse{}
	return resp
}
