// Code generated by "gen_req_resp.go"; DO NOT EDIT.
package serdes

type CacheGetConfigurationRequest struct {
	CacheId int32
	Flag    byte
}

type CacheGetConfigurationResponse struct {
	CacheConfiguration CacheConfiguration
}

func (req CacheGetConfigurationRequest) OpCode() int16 {
	return 1055
}

func (req CacheGetConfigurationRequest) Write(bw BinaryWriter) {
	bw.WriteInt32(req.CacheId)
	bw.WriteByte(req.Flag)
}

func (req CacheGetConfigurationRequest) ReadResponse(br BinaryReader) interface{} {
	resp := CacheGetConfigurationResponse{}
	resp.CacheConfiguration = ReadCacheConfiguration(br)
	return resp
}
