// Code generated by "gen_req_resp.go"; DO NOT EDIT.
package serdes

import "github.com/google/uuid"

type HandshakeRequest struct {
	Code           byte
	Major          int16
	Minor          int16
	Maintenance    int16
	ClientType     byte
	Features       *[]byte
	UserAttributes *map[string]string
	Username       *string
	Password       *string
}

type HandshakeResponse struct {
	Features *[]byte
	NodeId   *uuid.UUID
}

func (req HandshakeRequest) OpCode() int16 {
	return 1
}

func CreateHandshakeRequest() HandshakeRequest {
	return HandshakeRequest{Code: 1, Major: 1, Minor: 7, Maintenance: 0, ClientType: 2}
}

func (req HandshakeRequest) Write(buf *IgniteBuffer) {
	buf.WriteByte(req.Code)
	buf.WriteInt16(req.Major)
	buf.WriteInt16(req.Minor)
	buf.WriteInt16(req.Maintenance)
	buf.WriteByte(req.ClientType)
	buf.WriteByteArray(req.Features)
	buf.WriteStringString(req.UserAttributes)
	buf.WriteString(req.Username)
	buf.WriteString(req.Password)
}

func (req HandshakeRequest) ReadResponse(buf *IgniteBuffer) interface{} {
	resp := HandshakeResponse{}
	resp.Features = buf.ReadByteArray()
	resp.NodeId = buf.ReadUuid()
	return resp
}

type HandshakeFailResponse struct {
	Major       int16
	Minor       int16
	Maintenance int16
	Message     *string
	Code        byte
}

func (req HandshakeRequest) ReadFailResponse(buf *IgniteBuffer) interface{} {
	resp := HandshakeFailResponse{}
	resp.Major = buf.ReadInt16()
	resp.Minor = buf.ReadInt16()
	resp.Maintenance = buf.ReadInt16()
	resp.Message = buf.ReadString()
	resp.Code = buf.ReadByte()
	return resp
}
