// Code generated by "gen_req_resp.go"; DO NOT EDIT.
package serdes

type CacheGetConfigurationRequest struct {
	CacheId int32
	Flag    byte
}

type CacheGetConfigurationResponse struct {
	CacheConfiguration CacheConfiguration
}

func (req CacheGetConfigurationRequest) OpCode() int16 {
	return 1056
}

func (req CacheGetConfigurationRequest) Write(buf *IgniteBuffer) {
	buf.WriteInt32(req.CacheId)
	buf.WriteByte(req.Flag)
}

func (req CacheGetConfigurationRequest) ReadResponse(buf *IgniteBuffer) interface{} {
	resp := CacheGetConfigurationResponse{}
	resp.CacheConfiguration = buf.ReadCacheConfiguration()
	return resp
}
