// Code generated by "gen_req_resp.go"; DO NOT EDIT.
package serdes

type CacheGetOrCreateWithNameRequest struct {
	Cache *string
}

type CacheGetOrCreateWithNameResponse struct {
}

func (req CacheGetOrCreateWithNameRequest) OpCode() int16 {
	return 1052
}

func (req CacheGetOrCreateWithNameRequest) Write(bw BinaryWriter) {
	bw.WriteString(req.Cache)
}

func (req CacheGetOrCreateWithNameRequest) ReadResponse(br BinaryReader) interface{} {
	resp := CacheGetOrCreateWithNameResponse{}
	return resp
}
