// Code generated by "gen_req_resp.go"; DO NOT EDIT.
package serdes

import (
	"github.com/google/uuid"
)

func (buf *IgniteBuffer) WriteBoolBool0(m *map[bool]bool) {
	for key, val := range *m {
		buf.WriteBool(key)
		buf.WriteBool(val)
	}
}

func (buf *IgniteBuffer) WriteBoolBool(m *map[bool]bool) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteBoolBool0(m)
}

func (buf *IgniteBuffer) WriteBoolBoolWithoutType(m *map[bool]bool) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteBoolBool0(m)
}

func (buf *IgniteBuffer) ReadBoolBoolWithoutType() *map[bool]bool {
	res := make(map[bool]bool)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadBool()
		res[key] = buf.ReadBool()
	}
	return &res
}

func (buf *IgniteBuffer) ReadBoolBool() *map[bool]bool {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[bool]bool)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadBool()
		res[key] = buf.ReadBool()
	}
	return &res
}

func (buf *IgniteBuffer) WriteBoolByte0(m *map[bool]byte) {
	for key, val := range *m {
		buf.WriteBool(key)
		buf.WriteByte(val)
	}
}

func (buf *IgniteBuffer) WriteBoolByte(m *map[bool]byte) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteBoolByte0(m)
}

func (buf *IgniteBuffer) WriteBoolByteWithoutType(m *map[bool]byte) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteBoolByte0(m)
}

func (buf *IgniteBuffer) ReadBoolByteWithoutType() *map[bool]byte {
	res := make(map[bool]byte)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadBool()
		res[key] = buf.ReadByte()
	}
	return &res
}

func (buf *IgniteBuffer) ReadBoolByte() *map[bool]byte {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[bool]byte)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadBool()
		res[key] = buf.ReadByte()
	}
	return &res
}

func (buf *IgniteBuffer) WriteBoolByteArray0(m *map[bool][]byte) {
	for key, val := range *m {
		buf.WriteBool(key)
		buf.WriteByteArray(&val)
	}
}

func (buf *IgniteBuffer) WriteBoolByteArray(m *map[bool][]byte) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteBoolByteArray0(m)
}

func (buf *IgniteBuffer) WriteBoolByteArrayWithoutType(m *map[bool][]byte) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteBoolByteArray0(m)
}

func (buf *IgniteBuffer) ReadBoolByteArrayWithoutType() *map[bool][]byte {
	res := make(map[bool][]byte)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadBool()
		res[key] = *buf.ReadByteArray()
	}
	return &res
}

func (buf *IgniteBuffer) ReadBoolByteArray() *map[bool][]byte {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[bool][]byte)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadBool()
		res[key] = *buf.ReadByteArray()
	}
	return &res
}

func (buf *IgniteBuffer) WriteBoolInt320(m *map[bool]int32) {
	for key, val := range *m {
		buf.WriteBool(key)
		buf.WriteInt32(val)
	}
}

func (buf *IgniteBuffer) WriteBoolInt32(m *map[bool]int32) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteBoolInt320(m)
}

func (buf *IgniteBuffer) WriteBoolInt32WithoutType(m *map[bool]int32) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteBoolInt320(m)
}

func (buf *IgniteBuffer) ReadBoolInt32WithoutType() *map[bool]int32 {
	res := make(map[bool]int32)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadBool()
		res[key] = buf.ReadInt32()
	}
	return &res
}

func (buf *IgniteBuffer) ReadBoolInt32() *map[bool]int32 {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[bool]int32)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadBool()
		res[key] = buf.ReadInt32()
	}
	return &res
}

func (buf *IgniteBuffer) WriteBoolInt640(m *map[bool]int64) {
	for key, val := range *m {
		buf.WriteBool(key)
		buf.WriteInt64(val)
	}
}

func (buf *IgniteBuffer) WriteBoolInt64(m *map[bool]int64) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteBoolInt640(m)
}

func (buf *IgniteBuffer) WriteBoolInt64WithoutType(m *map[bool]int64) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteBoolInt640(m)
}

func (buf *IgniteBuffer) ReadBoolInt64WithoutType() *map[bool]int64 {
	res := make(map[bool]int64)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadBool()
		res[key] = buf.ReadInt64()
	}
	return &res
}

func (buf *IgniteBuffer) ReadBoolInt64() *map[bool]int64 {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[bool]int64)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadBool()
		res[key] = buf.ReadInt64()
	}
	return &res
}

func (buf *IgniteBuffer) WriteBoolInt160(m *map[bool]int16) {
	for key, val := range *m {
		buf.WriteBool(key)
		buf.WriteInt16(val)
	}
}

func (buf *IgniteBuffer) WriteBoolInt16(m *map[bool]int16) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteBoolInt160(m)
}

func (buf *IgniteBuffer) WriteBoolInt16WithoutType(m *map[bool]int16) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteBoolInt160(m)
}

func (buf *IgniteBuffer) ReadBoolInt16WithoutType() *map[bool]int16 {
	res := make(map[bool]int16)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadBool()
		res[key] = buf.ReadInt16()
	}
	return &res
}

func (buf *IgniteBuffer) ReadBoolInt16() *map[bool]int16 {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[bool]int16)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadBool()
		res[key] = buf.ReadInt16()
	}
	return &res
}

func (buf *IgniteBuffer) WriteBoolString0(m *map[bool]string) {
	for key, val := range *m {
		buf.WriteBool(key)
		buf.WriteString(&val)
	}
}

func (buf *IgniteBuffer) WriteBoolString(m *map[bool]string) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteBoolString0(m)
}

func (buf *IgniteBuffer) WriteBoolStringWithoutType(m *map[bool]string) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteBoolString0(m)
}

func (buf *IgniteBuffer) ReadBoolStringWithoutType() *map[bool]string {
	res := make(map[bool]string)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadBool()
		res[key] = *buf.ReadString()
	}
	return &res
}

func (buf *IgniteBuffer) ReadBoolString() *map[bool]string {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[bool]string)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadBool()
		res[key] = *buf.ReadString()
	}
	return &res
}

func (buf *IgniteBuffer) WriteBoolStringArray0(m *map[bool][]string) {
	for key, val := range *m {
		buf.WriteBool(key)
		buf.WriteStringArray(&val)
	}
}

func (buf *IgniteBuffer) WriteBoolStringArray(m *map[bool][]string) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteBoolStringArray0(m)
}

func (buf *IgniteBuffer) WriteBoolStringArrayWithoutType(m *map[bool][]string) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteBoolStringArray0(m)
}

func (buf *IgniteBuffer) ReadBoolStringArrayWithoutType() *map[bool][]string {
	res := make(map[bool][]string)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadBool()
		res[key] = *buf.ReadStringArray()
	}
	return &res
}

func (buf *IgniteBuffer) ReadBoolStringArray() *map[bool][]string {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[bool][]string)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadBool()
		res[key] = *buf.ReadStringArray()
	}
	return &res
}

func (buf *IgniteBuffer) WriteBoolUuid0(m *map[bool]uuid.UUID) {
	for key, val := range *m {
		buf.WriteBool(key)
		buf.WriteUuid(&val)
	}
}

func (buf *IgniteBuffer) WriteBoolUuid(m *map[bool]uuid.UUID) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteBoolUuid0(m)
}

func (buf *IgniteBuffer) WriteBoolUuidWithoutType(m *map[bool]uuid.UUID) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteBoolUuid0(m)
}

func (buf *IgniteBuffer) ReadBoolUuidWithoutType() *map[bool]uuid.UUID {
	res := make(map[bool]uuid.UUID)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadBool()
		res[key] = *buf.ReadUuid()
	}
	return &res
}

func (buf *IgniteBuffer) ReadBoolUuid() *map[bool]uuid.UUID {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[bool]uuid.UUID)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadBool()
		res[key] = *buf.ReadUuid()
	}
	return &res
}

func (buf *IgniteBuffer) WriteByteBool0(m *map[byte]bool) {
	for key, val := range *m {
		buf.WriteByte(key)
		buf.WriteBool(val)
	}
}

func (buf *IgniteBuffer) WriteByteBool(m *map[byte]bool) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteByteBool0(m)
}

func (buf *IgniteBuffer) WriteByteBoolWithoutType(m *map[byte]bool) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteByteBool0(m)
}

func (buf *IgniteBuffer) ReadByteBoolWithoutType() *map[byte]bool {
	res := make(map[byte]bool)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadByte()
		res[key] = buf.ReadBool()
	}
	return &res
}

func (buf *IgniteBuffer) ReadByteBool() *map[byte]bool {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[byte]bool)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadByte()
		res[key] = buf.ReadBool()
	}
	return &res
}

func (buf *IgniteBuffer) WriteByteByte0(m *map[byte]byte) {
	for key, val := range *m {
		buf.WriteByte(key)
		buf.WriteByte(val)
	}
}

func (buf *IgniteBuffer) WriteByteByte(m *map[byte]byte) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteByteByte0(m)
}

func (buf *IgniteBuffer) WriteByteByteWithoutType(m *map[byte]byte) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteByteByte0(m)
}

func (buf *IgniteBuffer) ReadByteByteWithoutType() *map[byte]byte {
	res := make(map[byte]byte)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadByte()
		res[key] = buf.ReadByte()
	}
	return &res
}

func (buf *IgniteBuffer) ReadByteByte() *map[byte]byte {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[byte]byte)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadByte()
		res[key] = buf.ReadByte()
	}
	return &res
}

func (buf *IgniteBuffer) WriteByteByteArray0(m *map[byte][]byte) {
	for key, val := range *m {
		buf.WriteByte(key)
		buf.WriteByteArray(&val)
	}
}

func (buf *IgniteBuffer) WriteByteByteArray(m *map[byte][]byte) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteByteByteArray0(m)
}

func (buf *IgniteBuffer) WriteByteByteArrayWithoutType(m *map[byte][]byte) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteByteByteArray0(m)
}

func (buf *IgniteBuffer) ReadByteByteArrayWithoutType() *map[byte][]byte {
	res := make(map[byte][]byte)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadByte()
		res[key] = *buf.ReadByteArray()
	}
	return &res
}

func (buf *IgniteBuffer) ReadByteByteArray() *map[byte][]byte {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[byte][]byte)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadByte()
		res[key] = *buf.ReadByteArray()
	}
	return &res
}

func (buf *IgniteBuffer) WriteByteInt320(m *map[byte]int32) {
	for key, val := range *m {
		buf.WriteByte(key)
		buf.WriteInt32(val)
	}
}

func (buf *IgniteBuffer) WriteByteInt32(m *map[byte]int32) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteByteInt320(m)
}

func (buf *IgniteBuffer) WriteByteInt32WithoutType(m *map[byte]int32) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteByteInt320(m)
}

func (buf *IgniteBuffer) ReadByteInt32WithoutType() *map[byte]int32 {
	res := make(map[byte]int32)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadByte()
		res[key] = buf.ReadInt32()
	}
	return &res
}

func (buf *IgniteBuffer) ReadByteInt32() *map[byte]int32 {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[byte]int32)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadByte()
		res[key] = buf.ReadInt32()
	}
	return &res
}

func (buf *IgniteBuffer) WriteByteInt640(m *map[byte]int64) {
	for key, val := range *m {
		buf.WriteByte(key)
		buf.WriteInt64(val)
	}
}

func (buf *IgniteBuffer) WriteByteInt64(m *map[byte]int64) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteByteInt640(m)
}

func (buf *IgniteBuffer) WriteByteInt64WithoutType(m *map[byte]int64) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteByteInt640(m)
}

func (buf *IgniteBuffer) ReadByteInt64WithoutType() *map[byte]int64 {
	res := make(map[byte]int64)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadByte()
		res[key] = buf.ReadInt64()
	}
	return &res
}

func (buf *IgniteBuffer) ReadByteInt64() *map[byte]int64 {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[byte]int64)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadByte()
		res[key] = buf.ReadInt64()
	}
	return &res
}

func (buf *IgniteBuffer) WriteByteInt160(m *map[byte]int16) {
	for key, val := range *m {
		buf.WriteByte(key)
		buf.WriteInt16(val)
	}
}

func (buf *IgniteBuffer) WriteByteInt16(m *map[byte]int16) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteByteInt160(m)
}

func (buf *IgniteBuffer) WriteByteInt16WithoutType(m *map[byte]int16) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteByteInt160(m)
}

func (buf *IgniteBuffer) ReadByteInt16WithoutType() *map[byte]int16 {
	res := make(map[byte]int16)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadByte()
		res[key] = buf.ReadInt16()
	}
	return &res
}

func (buf *IgniteBuffer) ReadByteInt16() *map[byte]int16 {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[byte]int16)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadByte()
		res[key] = buf.ReadInt16()
	}
	return &res
}

func (buf *IgniteBuffer) WriteByteString0(m *map[byte]string) {
	for key, val := range *m {
		buf.WriteByte(key)
		buf.WriteString(&val)
	}
}

func (buf *IgniteBuffer) WriteByteString(m *map[byte]string) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteByteString0(m)
}

func (buf *IgniteBuffer) WriteByteStringWithoutType(m *map[byte]string) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteByteString0(m)
}

func (buf *IgniteBuffer) ReadByteStringWithoutType() *map[byte]string {
	res := make(map[byte]string)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadByte()
		res[key] = *buf.ReadString()
	}
	return &res
}

func (buf *IgniteBuffer) ReadByteString() *map[byte]string {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[byte]string)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadByte()
		res[key] = *buf.ReadString()
	}
	return &res
}

func (buf *IgniteBuffer) WriteByteStringArray0(m *map[byte][]string) {
	for key, val := range *m {
		buf.WriteByte(key)
		buf.WriteStringArray(&val)
	}
}

func (buf *IgniteBuffer) WriteByteStringArray(m *map[byte][]string) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteByteStringArray0(m)
}

func (buf *IgniteBuffer) WriteByteStringArrayWithoutType(m *map[byte][]string) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteByteStringArray0(m)
}

func (buf *IgniteBuffer) ReadByteStringArrayWithoutType() *map[byte][]string {
	res := make(map[byte][]string)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadByte()
		res[key] = *buf.ReadStringArray()
	}
	return &res
}

func (buf *IgniteBuffer) ReadByteStringArray() *map[byte][]string {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[byte][]string)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadByte()
		res[key] = *buf.ReadStringArray()
	}
	return &res
}

func (buf *IgniteBuffer) WriteByteUuid0(m *map[byte]uuid.UUID) {
	for key, val := range *m {
		buf.WriteByte(key)
		buf.WriteUuid(&val)
	}
}

func (buf *IgniteBuffer) WriteByteUuid(m *map[byte]uuid.UUID) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteByteUuid0(m)
}

func (buf *IgniteBuffer) WriteByteUuidWithoutType(m *map[byte]uuid.UUID) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteByteUuid0(m)
}

func (buf *IgniteBuffer) ReadByteUuidWithoutType() *map[byte]uuid.UUID {
	res := make(map[byte]uuid.UUID)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadByte()
		res[key] = *buf.ReadUuid()
	}
	return &res
}

func (buf *IgniteBuffer) ReadByteUuid() *map[byte]uuid.UUID {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[byte]uuid.UUID)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadByte()
		res[key] = *buf.ReadUuid()
	}
	return &res
}

func (buf *IgniteBuffer) WriteInt32Bool0(m *map[int32]bool) {
	for key, val := range *m {
		buf.WriteInt32(key)
		buf.WriteBool(val)
	}
}

func (buf *IgniteBuffer) WriteInt32Bool(m *map[int32]bool) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteInt32Bool0(m)
}

func (buf *IgniteBuffer) WriteInt32BoolWithoutType(m *map[int32]bool) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteInt32Bool0(m)
}

func (buf *IgniteBuffer) ReadInt32BoolWithoutType() *map[int32]bool {
	res := make(map[int32]bool)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadInt32()
		res[key] = buf.ReadBool()
	}
	return &res
}

func (buf *IgniteBuffer) ReadInt32Bool() *map[int32]bool {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[int32]bool)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadInt32()
		res[key] = buf.ReadBool()
	}
	return &res
}

func (buf *IgniteBuffer) WriteInt32Byte0(m *map[int32]byte) {
	for key, val := range *m {
		buf.WriteInt32(key)
		buf.WriteByte(val)
	}
}

func (buf *IgniteBuffer) WriteInt32Byte(m *map[int32]byte) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteInt32Byte0(m)
}

func (buf *IgniteBuffer) WriteInt32ByteWithoutType(m *map[int32]byte) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteInt32Byte0(m)
}

func (buf *IgniteBuffer) ReadInt32ByteWithoutType() *map[int32]byte {
	res := make(map[int32]byte)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadInt32()
		res[key] = buf.ReadByte()
	}
	return &res
}

func (buf *IgniteBuffer) ReadInt32Byte() *map[int32]byte {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[int32]byte)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadInt32()
		res[key] = buf.ReadByte()
	}
	return &res
}

func (buf *IgniteBuffer) WriteInt32ByteArray0(m *map[int32][]byte) {
	for key, val := range *m {
		buf.WriteInt32(key)
		buf.WriteByteArray(&val)
	}
}

func (buf *IgniteBuffer) WriteInt32ByteArray(m *map[int32][]byte) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteInt32ByteArray0(m)
}

func (buf *IgniteBuffer) WriteInt32ByteArrayWithoutType(m *map[int32][]byte) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteInt32ByteArray0(m)
}

func (buf *IgniteBuffer) ReadInt32ByteArrayWithoutType() *map[int32][]byte {
	res := make(map[int32][]byte)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadInt32()
		res[key] = *buf.ReadByteArray()
	}
	return &res
}

func (buf *IgniteBuffer) ReadInt32ByteArray() *map[int32][]byte {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[int32][]byte)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadInt32()
		res[key] = *buf.ReadByteArray()
	}
	return &res
}

func (buf *IgniteBuffer) WriteInt32Int320(m *map[int32]int32) {
	for key, val := range *m {
		buf.WriteInt32(key)
		buf.WriteInt32(val)
	}
}

func (buf *IgniteBuffer) WriteInt32Int32(m *map[int32]int32) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteInt32Int320(m)
}

func (buf *IgniteBuffer) WriteInt32Int32WithoutType(m *map[int32]int32) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteInt32Int320(m)
}

func (buf *IgniteBuffer) ReadInt32Int32WithoutType() *map[int32]int32 {
	res := make(map[int32]int32)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadInt32()
		res[key] = buf.ReadInt32()
	}
	return &res
}

func (buf *IgniteBuffer) ReadInt32Int32() *map[int32]int32 {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[int32]int32)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadInt32()
		res[key] = buf.ReadInt32()
	}
	return &res
}

func (buf *IgniteBuffer) WriteInt32Int640(m *map[int32]int64) {
	for key, val := range *m {
		buf.WriteInt32(key)
		buf.WriteInt64(val)
	}
}

func (buf *IgniteBuffer) WriteInt32Int64(m *map[int32]int64) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteInt32Int640(m)
}

func (buf *IgniteBuffer) WriteInt32Int64WithoutType(m *map[int32]int64) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteInt32Int640(m)
}

func (buf *IgniteBuffer) ReadInt32Int64WithoutType() *map[int32]int64 {
	res := make(map[int32]int64)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadInt32()
		res[key] = buf.ReadInt64()
	}
	return &res
}

func (buf *IgniteBuffer) ReadInt32Int64() *map[int32]int64 {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[int32]int64)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadInt32()
		res[key] = buf.ReadInt64()
	}
	return &res
}

func (buf *IgniteBuffer) WriteInt32Int160(m *map[int32]int16) {
	for key, val := range *m {
		buf.WriteInt32(key)
		buf.WriteInt16(val)
	}
}

func (buf *IgniteBuffer) WriteInt32Int16(m *map[int32]int16) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteInt32Int160(m)
}

func (buf *IgniteBuffer) WriteInt32Int16WithoutType(m *map[int32]int16) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteInt32Int160(m)
}

func (buf *IgniteBuffer) ReadInt32Int16WithoutType() *map[int32]int16 {
	res := make(map[int32]int16)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadInt32()
		res[key] = buf.ReadInt16()
	}
	return &res
}

func (buf *IgniteBuffer) ReadInt32Int16() *map[int32]int16 {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[int32]int16)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadInt32()
		res[key] = buf.ReadInt16()
	}
	return &res
}

func (buf *IgniteBuffer) WriteInt32String0(m *map[int32]string) {
	for key, val := range *m {
		buf.WriteInt32(key)
		buf.WriteString(&val)
	}
}

func (buf *IgniteBuffer) WriteInt32String(m *map[int32]string) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteInt32String0(m)
}

func (buf *IgniteBuffer) WriteInt32StringWithoutType(m *map[int32]string) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteInt32String0(m)
}

func (buf *IgniteBuffer) ReadInt32StringWithoutType() *map[int32]string {
	res := make(map[int32]string)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadInt32()
		res[key] = *buf.ReadString()
	}
	return &res
}

func (buf *IgniteBuffer) ReadInt32String() *map[int32]string {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[int32]string)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadInt32()
		res[key] = *buf.ReadString()
	}
	return &res
}

func (buf *IgniteBuffer) WriteInt32StringArray0(m *map[int32][]string) {
	for key, val := range *m {
		buf.WriteInt32(key)
		buf.WriteStringArray(&val)
	}
}

func (buf *IgniteBuffer) WriteInt32StringArray(m *map[int32][]string) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteInt32StringArray0(m)
}

func (buf *IgniteBuffer) WriteInt32StringArrayWithoutType(m *map[int32][]string) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteInt32StringArray0(m)
}

func (buf *IgniteBuffer) ReadInt32StringArrayWithoutType() *map[int32][]string {
	res := make(map[int32][]string)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadInt32()
		res[key] = *buf.ReadStringArray()
	}
	return &res
}

func (buf *IgniteBuffer) ReadInt32StringArray() *map[int32][]string {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[int32][]string)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadInt32()
		res[key] = *buf.ReadStringArray()
	}
	return &res
}

func (buf *IgniteBuffer) WriteInt32Uuid0(m *map[int32]uuid.UUID) {
	for key, val := range *m {
		buf.WriteInt32(key)
		buf.WriteUuid(&val)
	}
}

func (buf *IgniteBuffer) WriteInt32Uuid(m *map[int32]uuid.UUID) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteInt32Uuid0(m)
}

func (buf *IgniteBuffer) WriteInt32UuidWithoutType(m *map[int32]uuid.UUID) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteInt32Uuid0(m)
}

func (buf *IgniteBuffer) ReadInt32UuidWithoutType() *map[int32]uuid.UUID {
	res := make(map[int32]uuid.UUID)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadInt32()
		res[key] = *buf.ReadUuid()
	}
	return &res
}

func (buf *IgniteBuffer) ReadInt32Uuid() *map[int32]uuid.UUID {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[int32]uuid.UUID)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadInt32()
		res[key] = *buf.ReadUuid()
	}
	return &res
}

func (buf *IgniteBuffer) WriteInt64Bool0(m *map[int64]bool) {
	for key, val := range *m {
		buf.WriteInt64(key)
		buf.WriteBool(val)
	}
}

func (buf *IgniteBuffer) WriteInt64Bool(m *map[int64]bool) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteInt64Bool0(m)
}

func (buf *IgniteBuffer) WriteInt64BoolWithoutType(m *map[int64]bool) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteInt64Bool0(m)
}

func (buf *IgniteBuffer) ReadInt64BoolWithoutType() *map[int64]bool {
	res := make(map[int64]bool)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadInt64()
		res[key] = buf.ReadBool()
	}
	return &res
}

func (buf *IgniteBuffer) ReadInt64Bool() *map[int64]bool {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[int64]bool)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadInt64()
		res[key] = buf.ReadBool()
	}
	return &res
}

func (buf *IgniteBuffer) WriteInt64Byte0(m *map[int64]byte) {
	for key, val := range *m {
		buf.WriteInt64(key)
		buf.WriteByte(val)
	}
}

func (buf *IgniteBuffer) WriteInt64Byte(m *map[int64]byte) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteInt64Byte0(m)
}

func (buf *IgniteBuffer) WriteInt64ByteWithoutType(m *map[int64]byte) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteInt64Byte0(m)
}

func (buf *IgniteBuffer) ReadInt64ByteWithoutType() *map[int64]byte {
	res := make(map[int64]byte)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadInt64()
		res[key] = buf.ReadByte()
	}
	return &res
}

func (buf *IgniteBuffer) ReadInt64Byte() *map[int64]byte {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[int64]byte)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadInt64()
		res[key] = buf.ReadByte()
	}
	return &res
}

func (buf *IgniteBuffer) WriteInt64ByteArray0(m *map[int64][]byte) {
	for key, val := range *m {
		buf.WriteInt64(key)
		buf.WriteByteArray(&val)
	}
}

func (buf *IgniteBuffer) WriteInt64ByteArray(m *map[int64][]byte) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteInt64ByteArray0(m)
}

func (buf *IgniteBuffer) WriteInt64ByteArrayWithoutType(m *map[int64][]byte) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteInt64ByteArray0(m)
}

func (buf *IgniteBuffer) ReadInt64ByteArrayWithoutType() *map[int64][]byte {
	res := make(map[int64][]byte)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadInt64()
		res[key] = *buf.ReadByteArray()
	}
	return &res
}

func (buf *IgniteBuffer) ReadInt64ByteArray() *map[int64][]byte {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[int64][]byte)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadInt64()
		res[key] = *buf.ReadByteArray()
	}
	return &res
}

func (buf *IgniteBuffer) WriteInt64Int320(m *map[int64]int32) {
	for key, val := range *m {
		buf.WriteInt64(key)
		buf.WriteInt32(val)
	}
}

func (buf *IgniteBuffer) WriteInt64Int32(m *map[int64]int32) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteInt64Int320(m)
}

func (buf *IgniteBuffer) WriteInt64Int32WithoutType(m *map[int64]int32) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteInt64Int320(m)
}

func (buf *IgniteBuffer) ReadInt64Int32WithoutType() *map[int64]int32 {
	res := make(map[int64]int32)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadInt64()
		res[key] = buf.ReadInt32()
	}
	return &res
}

func (buf *IgniteBuffer) ReadInt64Int32() *map[int64]int32 {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[int64]int32)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadInt64()
		res[key] = buf.ReadInt32()
	}
	return &res
}

func (buf *IgniteBuffer) WriteInt64Int640(m *map[int64]int64) {
	for key, val := range *m {
		buf.WriteInt64(key)
		buf.WriteInt64(val)
	}
}

func (buf *IgniteBuffer) WriteInt64Int64(m *map[int64]int64) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteInt64Int640(m)
}

func (buf *IgniteBuffer) WriteInt64Int64WithoutType(m *map[int64]int64) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteInt64Int640(m)
}

func (buf *IgniteBuffer) ReadInt64Int64WithoutType() *map[int64]int64 {
	res := make(map[int64]int64)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadInt64()
		res[key] = buf.ReadInt64()
	}
	return &res
}

func (buf *IgniteBuffer) ReadInt64Int64() *map[int64]int64 {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[int64]int64)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadInt64()
		res[key] = buf.ReadInt64()
	}
	return &res
}

func (buf *IgniteBuffer) WriteInt64Int160(m *map[int64]int16) {
	for key, val := range *m {
		buf.WriteInt64(key)
		buf.WriteInt16(val)
	}
}

func (buf *IgniteBuffer) WriteInt64Int16(m *map[int64]int16) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteInt64Int160(m)
}

func (buf *IgniteBuffer) WriteInt64Int16WithoutType(m *map[int64]int16) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteInt64Int160(m)
}

func (buf *IgniteBuffer) ReadInt64Int16WithoutType() *map[int64]int16 {
	res := make(map[int64]int16)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadInt64()
		res[key] = buf.ReadInt16()
	}
	return &res
}

func (buf *IgniteBuffer) ReadInt64Int16() *map[int64]int16 {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[int64]int16)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadInt64()
		res[key] = buf.ReadInt16()
	}
	return &res
}

func (buf *IgniteBuffer) WriteInt64String0(m *map[int64]string) {
	for key, val := range *m {
		buf.WriteInt64(key)
		buf.WriteString(&val)
	}
}

func (buf *IgniteBuffer) WriteInt64String(m *map[int64]string) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteInt64String0(m)
}

func (buf *IgniteBuffer) WriteInt64StringWithoutType(m *map[int64]string) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteInt64String0(m)
}

func (buf *IgniteBuffer) ReadInt64StringWithoutType() *map[int64]string {
	res := make(map[int64]string)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadInt64()
		res[key] = *buf.ReadString()
	}
	return &res
}

func (buf *IgniteBuffer) ReadInt64String() *map[int64]string {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[int64]string)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadInt64()
		res[key] = *buf.ReadString()
	}
	return &res
}

func (buf *IgniteBuffer) WriteInt64StringArray0(m *map[int64][]string) {
	for key, val := range *m {
		buf.WriteInt64(key)
		buf.WriteStringArray(&val)
	}
}

func (buf *IgniteBuffer) WriteInt64StringArray(m *map[int64][]string) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteInt64StringArray0(m)
}

func (buf *IgniteBuffer) WriteInt64StringArrayWithoutType(m *map[int64][]string) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteInt64StringArray0(m)
}

func (buf *IgniteBuffer) ReadInt64StringArrayWithoutType() *map[int64][]string {
	res := make(map[int64][]string)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadInt64()
		res[key] = *buf.ReadStringArray()
	}
	return &res
}

func (buf *IgniteBuffer) ReadInt64StringArray() *map[int64][]string {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[int64][]string)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadInt64()
		res[key] = *buf.ReadStringArray()
	}
	return &res
}

func (buf *IgniteBuffer) WriteInt64Uuid0(m *map[int64]uuid.UUID) {
	for key, val := range *m {
		buf.WriteInt64(key)
		buf.WriteUuid(&val)
	}
}

func (buf *IgniteBuffer) WriteInt64Uuid(m *map[int64]uuid.UUID) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteInt64Uuid0(m)
}

func (buf *IgniteBuffer) WriteInt64UuidWithoutType(m *map[int64]uuid.UUID) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteInt64Uuid0(m)
}

func (buf *IgniteBuffer) ReadInt64UuidWithoutType() *map[int64]uuid.UUID {
	res := make(map[int64]uuid.UUID)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadInt64()
		res[key] = *buf.ReadUuid()
	}
	return &res
}

func (buf *IgniteBuffer) ReadInt64Uuid() *map[int64]uuid.UUID {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[int64]uuid.UUID)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadInt64()
		res[key] = *buf.ReadUuid()
	}
	return &res
}

func (buf *IgniteBuffer) WriteInt16Bool0(m *map[int16]bool) {
	for key, val := range *m {
		buf.WriteInt16(key)
		buf.WriteBool(val)
	}
}

func (buf *IgniteBuffer) WriteInt16Bool(m *map[int16]bool) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteInt16Bool0(m)
}

func (buf *IgniteBuffer) WriteInt16BoolWithoutType(m *map[int16]bool) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteInt16Bool0(m)
}

func (buf *IgniteBuffer) ReadInt16BoolWithoutType() *map[int16]bool {
	res := make(map[int16]bool)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadInt16()
		res[key] = buf.ReadBool()
	}
	return &res
}

func (buf *IgniteBuffer) ReadInt16Bool() *map[int16]bool {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[int16]bool)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadInt16()
		res[key] = buf.ReadBool()
	}
	return &res
}

func (buf *IgniteBuffer) WriteInt16Byte0(m *map[int16]byte) {
	for key, val := range *m {
		buf.WriteInt16(key)
		buf.WriteByte(val)
	}
}

func (buf *IgniteBuffer) WriteInt16Byte(m *map[int16]byte) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteInt16Byte0(m)
}

func (buf *IgniteBuffer) WriteInt16ByteWithoutType(m *map[int16]byte) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteInt16Byte0(m)
}

func (buf *IgniteBuffer) ReadInt16ByteWithoutType() *map[int16]byte {
	res := make(map[int16]byte)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadInt16()
		res[key] = buf.ReadByte()
	}
	return &res
}

func (buf *IgniteBuffer) ReadInt16Byte() *map[int16]byte {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[int16]byte)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadInt16()
		res[key] = buf.ReadByte()
	}
	return &res
}

func (buf *IgniteBuffer) WriteInt16ByteArray0(m *map[int16][]byte) {
	for key, val := range *m {
		buf.WriteInt16(key)
		buf.WriteByteArray(&val)
	}
}

func (buf *IgniteBuffer) WriteInt16ByteArray(m *map[int16][]byte) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteInt16ByteArray0(m)
}

func (buf *IgniteBuffer) WriteInt16ByteArrayWithoutType(m *map[int16][]byte) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteInt16ByteArray0(m)
}

func (buf *IgniteBuffer) ReadInt16ByteArrayWithoutType() *map[int16][]byte {
	res := make(map[int16][]byte)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadInt16()
		res[key] = *buf.ReadByteArray()
	}
	return &res
}

func (buf *IgniteBuffer) ReadInt16ByteArray() *map[int16][]byte {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[int16][]byte)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadInt16()
		res[key] = *buf.ReadByteArray()
	}
	return &res
}

func (buf *IgniteBuffer) WriteInt16Int320(m *map[int16]int32) {
	for key, val := range *m {
		buf.WriteInt16(key)
		buf.WriteInt32(val)
	}
}

func (buf *IgniteBuffer) WriteInt16Int32(m *map[int16]int32) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteInt16Int320(m)
}

func (buf *IgniteBuffer) WriteInt16Int32WithoutType(m *map[int16]int32) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteInt16Int320(m)
}

func (buf *IgniteBuffer) ReadInt16Int32WithoutType() *map[int16]int32 {
	res := make(map[int16]int32)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadInt16()
		res[key] = buf.ReadInt32()
	}
	return &res
}

func (buf *IgniteBuffer) ReadInt16Int32() *map[int16]int32 {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[int16]int32)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadInt16()
		res[key] = buf.ReadInt32()
	}
	return &res
}

func (buf *IgniteBuffer) WriteInt16Int640(m *map[int16]int64) {
	for key, val := range *m {
		buf.WriteInt16(key)
		buf.WriteInt64(val)
	}
}

func (buf *IgniteBuffer) WriteInt16Int64(m *map[int16]int64) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteInt16Int640(m)
}

func (buf *IgniteBuffer) WriteInt16Int64WithoutType(m *map[int16]int64) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteInt16Int640(m)
}

func (buf *IgniteBuffer) ReadInt16Int64WithoutType() *map[int16]int64 {
	res := make(map[int16]int64)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadInt16()
		res[key] = buf.ReadInt64()
	}
	return &res
}

func (buf *IgniteBuffer) ReadInt16Int64() *map[int16]int64 {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[int16]int64)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadInt16()
		res[key] = buf.ReadInt64()
	}
	return &res
}

func (buf *IgniteBuffer) WriteInt16Int160(m *map[int16]int16) {
	for key, val := range *m {
		buf.WriteInt16(key)
		buf.WriteInt16(val)
	}
}

func (buf *IgniteBuffer) WriteInt16Int16(m *map[int16]int16) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteInt16Int160(m)
}

func (buf *IgniteBuffer) WriteInt16Int16WithoutType(m *map[int16]int16) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteInt16Int160(m)
}

func (buf *IgniteBuffer) ReadInt16Int16WithoutType() *map[int16]int16 {
	res := make(map[int16]int16)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadInt16()
		res[key] = buf.ReadInt16()
	}
	return &res
}

func (buf *IgniteBuffer) ReadInt16Int16() *map[int16]int16 {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[int16]int16)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadInt16()
		res[key] = buf.ReadInt16()
	}
	return &res
}

func (buf *IgniteBuffer) WriteInt16String0(m *map[int16]string) {
	for key, val := range *m {
		buf.WriteInt16(key)
		buf.WriteString(&val)
	}
}

func (buf *IgniteBuffer) WriteInt16String(m *map[int16]string) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteInt16String0(m)
}

func (buf *IgniteBuffer) WriteInt16StringWithoutType(m *map[int16]string) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteInt16String0(m)
}

func (buf *IgniteBuffer) ReadInt16StringWithoutType() *map[int16]string {
	res := make(map[int16]string)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadInt16()
		res[key] = *buf.ReadString()
	}
	return &res
}

func (buf *IgniteBuffer) ReadInt16String() *map[int16]string {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[int16]string)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadInt16()
		res[key] = *buf.ReadString()
	}
	return &res
}

func (buf *IgniteBuffer) WriteInt16StringArray0(m *map[int16][]string) {
	for key, val := range *m {
		buf.WriteInt16(key)
		buf.WriteStringArray(&val)
	}
}

func (buf *IgniteBuffer) WriteInt16StringArray(m *map[int16][]string) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteInt16StringArray0(m)
}

func (buf *IgniteBuffer) WriteInt16StringArrayWithoutType(m *map[int16][]string) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteInt16StringArray0(m)
}

func (buf *IgniteBuffer) ReadInt16StringArrayWithoutType() *map[int16][]string {
	res := make(map[int16][]string)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadInt16()
		res[key] = *buf.ReadStringArray()
	}
	return &res
}

func (buf *IgniteBuffer) ReadInt16StringArray() *map[int16][]string {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[int16][]string)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadInt16()
		res[key] = *buf.ReadStringArray()
	}
	return &res
}

func (buf *IgniteBuffer) WriteInt16Uuid0(m *map[int16]uuid.UUID) {
	for key, val := range *m {
		buf.WriteInt16(key)
		buf.WriteUuid(&val)
	}
}

func (buf *IgniteBuffer) WriteInt16Uuid(m *map[int16]uuid.UUID) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteInt16Uuid0(m)
}

func (buf *IgniteBuffer) WriteInt16UuidWithoutType(m *map[int16]uuid.UUID) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteInt16Uuid0(m)
}

func (buf *IgniteBuffer) ReadInt16UuidWithoutType() *map[int16]uuid.UUID {
	res := make(map[int16]uuid.UUID)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := buf.ReadInt16()
		res[key] = *buf.ReadUuid()
	}
	return &res
}

func (buf *IgniteBuffer) ReadInt16Uuid() *map[int16]uuid.UUID {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[int16]uuid.UUID)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := buf.ReadInt16()
		res[key] = *buf.ReadUuid()
	}
	return &res
}

func (buf *IgniteBuffer) WriteStringBool0(m *map[string]bool) {
	for key, val := range *m {
		buf.WriteString(&key)
		buf.WriteBool(val)
	}
}

func (buf *IgniteBuffer) WriteStringBool(m *map[string]bool) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteStringBool0(m)
}

func (buf *IgniteBuffer) WriteStringBoolWithoutType(m *map[string]bool) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteStringBool0(m)
}

func (buf *IgniteBuffer) ReadStringBoolWithoutType() *map[string]bool {
	res := make(map[string]bool)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := *buf.ReadString()
		res[key] = buf.ReadBool()
	}
	return &res
}

func (buf *IgniteBuffer) ReadStringBool() *map[string]bool {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[string]bool)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := *buf.ReadString()
		res[key] = buf.ReadBool()
	}
	return &res
}

func (buf *IgniteBuffer) WriteStringByte0(m *map[string]byte) {
	for key, val := range *m {
		buf.WriteString(&key)
		buf.WriteByte(val)
	}
}

func (buf *IgniteBuffer) WriteStringByte(m *map[string]byte) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteStringByte0(m)
}

func (buf *IgniteBuffer) WriteStringByteWithoutType(m *map[string]byte) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteStringByte0(m)
}

func (buf *IgniteBuffer) ReadStringByteWithoutType() *map[string]byte {
	res := make(map[string]byte)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := *buf.ReadString()
		res[key] = buf.ReadByte()
	}
	return &res
}

func (buf *IgniteBuffer) ReadStringByte() *map[string]byte {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[string]byte)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := *buf.ReadString()
		res[key] = buf.ReadByte()
	}
	return &res
}

func (buf *IgniteBuffer) WriteStringByteArray0(m *map[string][]byte) {
	for key, val := range *m {
		buf.WriteString(&key)
		buf.WriteByteArray(&val)
	}
}

func (buf *IgniteBuffer) WriteStringByteArray(m *map[string][]byte) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteStringByteArray0(m)
}

func (buf *IgniteBuffer) WriteStringByteArrayWithoutType(m *map[string][]byte) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteStringByteArray0(m)
}

func (buf *IgniteBuffer) ReadStringByteArrayWithoutType() *map[string][]byte {
	res := make(map[string][]byte)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := *buf.ReadString()
		res[key] = *buf.ReadByteArray()
	}
	return &res
}

func (buf *IgniteBuffer) ReadStringByteArray() *map[string][]byte {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[string][]byte)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := *buf.ReadString()
		res[key] = *buf.ReadByteArray()
	}
	return &res
}

func (buf *IgniteBuffer) WriteStringInt320(m *map[string]int32) {
	for key, val := range *m {
		buf.WriteString(&key)
		buf.WriteInt32(val)
	}
}

func (buf *IgniteBuffer) WriteStringInt32(m *map[string]int32) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteStringInt320(m)
}

func (buf *IgniteBuffer) WriteStringInt32WithoutType(m *map[string]int32) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteStringInt320(m)
}

func (buf *IgniteBuffer) ReadStringInt32WithoutType() *map[string]int32 {
	res := make(map[string]int32)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := *buf.ReadString()
		res[key] = buf.ReadInt32()
	}
	return &res
}

func (buf *IgniteBuffer) ReadStringInt32() *map[string]int32 {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[string]int32)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := *buf.ReadString()
		res[key] = buf.ReadInt32()
	}
	return &res
}

func (buf *IgniteBuffer) WriteStringInt640(m *map[string]int64) {
	for key, val := range *m {
		buf.WriteString(&key)
		buf.WriteInt64(val)
	}
}

func (buf *IgniteBuffer) WriteStringInt64(m *map[string]int64) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteStringInt640(m)
}

func (buf *IgniteBuffer) WriteStringInt64WithoutType(m *map[string]int64) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteStringInt640(m)
}

func (buf *IgniteBuffer) ReadStringInt64WithoutType() *map[string]int64 {
	res := make(map[string]int64)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := *buf.ReadString()
		res[key] = buf.ReadInt64()
	}
	return &res
}

func (buf *IgniteBuffer) ReadStringInt64() *map[string]int64 {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[string]int64)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := *buf.ReadString()
		res[key] = buf.ReadInt64()
	}
	return &res
}

func (buf *IgniteBuffer) WriteStringInt160(m *map[string]int16) {
	for key, val := range *m {
		buf.WriteString(&key)
		buf.WriteInt16(val)
	}
}

func (buf *IgniteBuffer) WriteStringInt16(m *map[string]int16) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteStringInt160(m)
}

func (buf *IgniteBuffer) WriteStringInt16WithoutType(m *map[string]int16) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteStringInt160(m)
}

func (buf *IgniteBuffer) ReadStringInt16WithoutType() *map[string]int16 {
	res := make(map[string]int16)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := *buf.ReadString()
		res[key] = buf.ReadInt16()
	}
	return &res
}

func (buf *IgniteBuffer) ReadStringInt16() *map[string]int16 {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[string]int16)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := *buf.ReadString()
		res[key] = buf.ReadInt16()
	}
	return &res
}

func (buf *IgniteBuffer) WriteStringString0(m *map[string]string) {
	for key, val := range *m {
		buf.WriteString(&key)
		buf.WriteString(&val)
	}
}

func (buf *IgniteBuffer) WriteStringString(m *map[string]string) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteStringString0(m)
}

func (buf *IgniteBuffer) WriteStringStringWithoutType(m *map[string]string) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteStringString0(m)
}

func (buf *IgniteBuffer) ReadStringStringWithoutType() *map[string]string {
	res := make(map[string]string)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := *buf.ReadString()
		res[key] = *buf.ReadString()
	}
	return &res
}

func (buf *IgniteBuffer) ReadStringString() *map[string]string {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[string]string)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := *buf.ReadString()
		res[key] = *buf.ReadString()
	}
	return &res
}

func (buf *IgniteBuffer) WriteStringStringArray0(m *map[string][]string) {
	for key, val := range *m {
		buf.WriteString(&key)
		buf.WriteStringArray(&val)
	}
}

func (buf *IgniteBuffer) WriteStringStringArray(m *map[string][]string) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteStringStringArray0(m)
}

func (buf *IgniteBuffer) WriteStringStringArrayWithoutType(m *map[string][]string) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteStringStringArray0(m)
}

func (buf *IgniteBuffer) ReadStringStringArrayWithoutType() *map[string][]string {
	res := make(map[string][]string)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := *buf.ReadString()
		res[key] = *buf.ReadStringArray()
	}
	return &res
}

func (buf *IgniteBuffer) ReadStringStringArray() *map[string][]string {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[string][]string)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := *buf.ReadString()
		res[key] = *buf.ReadStringArray()
	}
	return &res
}

func (buf *IgniteBuffer) WriteStringUuid0(m *map[string]uuid.UUID) {
	for key, val := range *m {
		buf.WriteString(&key)
		buf.WriteUuid(&val)
	}
}

func (buf *IgniteBuffer) WriteStringUuid(m *map[string]uuid.UUID) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteStringUuid0(m)
}

func (buf *IgniteBuffer) WriteStringUuidWithoutType(m *map[string]uuid.UUID) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteStringUuid0(m)
}

func (buf *IgniteBuffer) ReadStringUuidWithoutType() *map[string]uuid.UUID {
	res := make(map[string]uuid.UUID)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := *buf.ReadString()
		res[key] = *buf.ReadUuid()
	}
	return &res
}

func (buf *IgniteBuffer) ReadStringUuid() *map[string]uuid.UUID {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[string]uuid.UUID)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := *buf.ReadString()
		res[key] = *buf.ReadUuid()
	}
	return &res
}

func (buf *IgniteBuffer) WriteUuidBool0(m *map[uuid.UUID]bool) {
	for key, val := range *m {
		buf.WriteUuid(&key)
		buf.WriteBool(val)
	}
}

func (buf *IgniteBuffer) WriteUuidBool(m *map[uuid.UUID]bool) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteUuidBool0(m)
}

func (buf *IgniteBuffer) WriteUuidBoolWithoutType(m *map[uuid.UUID]bool) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteUuidBool0(m)
}

func (buf *IgniteBuffer) ReadUuidBoolWithoutType() *map[uuid.UUID]bool {
	res := make(map[uuid.UUID]bool)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := *buf.ReadUuid()
		res[key] = buf.ReadBool()
	}
	return &res
}

func (buf *IgniteBuffer) ReadUuidBool() *map[uuid.UUID]bool {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[uuid.UUID]bool)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := *buf.ReadUuid()
		res[key] = buf.ReadBool()
	}
	return &res
}

func (buf *IgniteBuffer) WriteUuidByte0(m *map[uuid.UUID]byte) {
	for key, val := range *m {
		buf.WriteUuid(&key)
		buf.WriteByte(val)
	}
}

func (buf *IgniteBuffer) WriteUuidByte(m *map[uuid.UUID]byte) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteUuidByte0(m)
}

func (buf *IgniteBuffer) WriteUuidByteWithoutType(m *map[uuid.UUID]byte) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteUuidByte0(m)
}

func (buf *IgniteBuffer) ReadUuidByteWithoutType() *map[uuid.UUID]byte {
	res := make(map[uuid.UUID]byte)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := *buf.ReadUuid()
		res[key] = buf.ReadByte()
	}
	return &res
}

func (buf *IgniteBuffer) ReadUuidByte() *map[uuid.UUID]byte {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[uuid.UUID]byte)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := *buf.ReadUuid()
		res[key] = buf.ReadByte()
	}
	return &res
}

func (buf *IgniteBuffer) WriteUuidByteArray0(m *map[uuid.UUID][]byte) {
	for key, val := range *m {
		buf.WriteUuid(&key)
		buf.WriteByteArray(&val)
	}
}

func (buf *IgniteBuffer) WriteUuidByteArray(m *map[uuid.UUID][]byte) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteUuidByteArray0(m)
}

func (buf *IgniteBuffer) WriteUuidByteArrayWithoutType(m *map[uuid.UUID][]byte) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteUuidByteArray0(m)
}

func (buf *IgniteBuffer) ReadUuidByteArrayWithoutType() *map[uuid.UUID][]byte {
	res := make(map[uuid.UUID][]byte)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := *buf.ReadUuid()
		res[key] = *buf.ReadByteArray()
	}
	return &res
}

func (buf *IgniteBuffer) ReadUuidByteArray() *map[uuid.UUID][]byte {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[uuid.UUID][]byte)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := *buf.ReadUuid()
		res[key] = *buf.ReadByteArray()
	}
	return &res
}

func (buf *IgniteBuffer) WriteUuidInt320(m *map[uuid.UUID]int32) {
	for key, val := range *m {
		buf.WriteUuid(&key)
		buf.WriteInt32(val)
	}
}

func (buf *IgniteBuffer) WriteUuidInt32(m *map[uuid.UUID]int32) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteUuidInt320(m)
}

func (buf *IgniteBuffer) WriteUuidInt32WithoutType(m *map[uuid.UUID]int32) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteUuidInt320(m)
}

func (buf *IgniteBuffer) ReadUuidInt32WithoutType() *map[uuid.UUID]int32 {
	res := make(map[uuid.UUID]int32)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := *buf.ReadUuid()
		res[key] = buf.ReadInt32()
	}
	return &res
}

func (buf *IgniteBuffer) ReadUuidInt32() *map[uuid.UUID]int32 {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[uuid.UUID]int32)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := *buf.ReadUuid()
		res[key] = buf.ReadInt32()
	}
	return &res
}

func (buf *IgniteBuffer) WriteUuidInt640(m *map[uuid.UUID]int64) {
	for key, val := range *m {
		buf.WriteUuid(&key)
		buf.WriteInt64(val)
	}
}

func (buf *IgniteBuffer) WriteUuidInt64(m *map[uuid.UUID]int64) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteUuidInt640(m)
}

func (buf *IgniteBuffer) WriteUuidInt64WithoutType(m *map[uuid.UUID]int64) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteUuidInt640(m)
}

func (buf *IgniteBuffer) ReadUuidInt64WithoutType() *map[uuid.UUID]int64 {
	res := make(map[uuid.UUID]int64)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := *buf.ReadUuid()
		res[key] = buf.ReadInt64()
	}
	return &res
}

func (buf *IgniteBuffer) ReadUuidInt64() *map[uuid.UUID]int64 {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[uuid.UUID]int64)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := *buf.ReadUuid()
		res[key] = buf.ReadInt64()
	}
	return &res
}

func (buf *IgniteBuffer) WriteUuidInt160(m *map[uuid.UUID]int16) {
	for key, val := range *m {
		buf.WriteUuid(&key)
		buf.WriteInt16(val)
	}
}

func (buf *IgniteBuffer) WriteUuidInt16(m *map[uuid.UUID]int16) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteUuidInt160(m)
}

func (buf *IgniteBuffer) WriteUuidInt16WithoutType(m *map[uuid.UUID]int16) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteUuidInt160(m)
}

func (buf *IgniteBuffer) ReadUuidInt16WithoutType() *map[uuid.UUID]int16 {
	res := make(map[uuid.UUID]int16)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := *buf.ReadUuid()
		res[key] = buf.ReadInt16()
	}
	return &res
}

func (buf *IgniteBuffer) ReadUuidInt16() *map[uuid.UUID]int16 {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[uuid.UUID]int16)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := *buf.ReadUuid()
		res[key] = buf.ReadInt16()
	}
	return &res
}

func (buf *IgniteBuffer) WriteUuidString0(m *map[uuid.UUID]string) {
	for key, val := range *m {
		buf.WriteUuid(&key)
		buf.WriteString(&val)
	}
}

func (buf *IgniteBuffer) WriteUuidString(m *map[uuid.UUID]string) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteUuidString0(m)
}

func (buf *IgniteBuffer) WriteUuidStringWithoutType(m *map[uuid.UUID]string) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteUuidString0(m)
}

func (buf *IgniteBuffer) ReadUuidStringWithoutType() *map[uuid.UUID]string {
	res := make(map[uuid.UUID]string)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := *buf.ReadUuid()
		res[key] = *buf.ReadString()
	}
	return &res
}

func (buf *IgniteBuffer) ReadUuidString() *map[uuid.UUID]string {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[uuid.UUID]string)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := *buf.ReadUuid()
		res[key] = *buf.ReadString()
	}
	return &res
}

func (buf *IgniteBuffer) WriteUuidStringArray0(m *map[uuid.UUID][]string) {
	for key, val := range *m {
		buf.WriteUuid(&key)
		buf.WriteStringArray(&val)
	}
}

func (buf *IgniteBuffer) WriteUuidStringArray(m *map[uuid.UUID][]string) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteUuidStringArray0(m)
}

func (buf *IgniteBuffer) WriteUuidStringArrayWithoutType(m *map[uuid.UUID][]string) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteUuidStringArray0(m)
}

func (buf *IgniteBuffer) ReadUuidStringArrayWithoutType() *map[uuid.UUID][]string {
	res := make(map[uuid.UUID][]string)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := *buf.ReadUuid()
		res[key] = *buf.ReadStringArray()
	}
	return &res
}

func (buf *IgniteBuffer) ReadUuidStringArray() *map[uuid.UUID][]string {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[uuid.UUID][]string)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := *buf.ReadUuid()
		res[key] = *buf.ReadStringArray()
	}
	return &res
}

func (buf *IgniteBuffer) WriteUuidUuid0(m *map[uuid.UUID]uuid.UUID) {
	for key, val := range *m {
		buf.WriteUuid(&key)
		buf.WriteUuid(&val)
	}
}

func (buf *IgniteBuffer) WriteUuidUuid(m *map[uuid.UUID]uuid.UUID) {
	if m == nil {
		buf.WriteByte(Null)
		return
	}
	WriteMapHeader(buf, len(*m))
	buf.WriteUuidUuid0(m)
}

func (buf *IgniteBuffer) WriteUuidUuidWithoutType(m *map[uuid.UUID]uuid.UUID) {
	if m == nil {
		buf.WriteInt(0)
		return
	}
	buf.WriteInt(len(*m))
	buf.WriteUuidUuid0(m)
}

func (buf *IgniteBuffer) ReadUuidUuidWithoutType() *map[uuid.UUID]uuid.UUID {
	res := make(map[uuid.UUID]uuid.UUID)
	l := int(buf.ReadInt32())
	for i := 0; i < l; i++ {
		key := *buf.ReadUuid()
		res[key] = *buf.ReadUuid()
	}
	return &res
}

func (buf *IgniteBuffer) ReadUuidUuid() *map[uuid.UUID]uuid.UUID {
	if buf.EnsureMapType() {
		return nil
	}
	res := make(map[uuid.UUID]uuid.UUID)
	l := int(buf.ReadInt32())
	buf.ReadByte()
	for i := 0; i < l; i++ {
		key := *buf.ReadUuid()
		res[key] = *buf.ReadUuid()
	}
	return &res
}
