// Code generated by "gen_req_resp.go"; DO NOT EDIT.
package serdes

import "github.com/google/uuid"

type HandshakeRequest struct {
	Code           byte
	Major          int16
	Minor          int16
	Maintenance    int16
	ClientType     byte
	Features       []byte
	UserAttributes map[string]*string
	Username       *string
	Password       *string
}

type HandshakeResponse struct {
	Features []byte
	NodeId   *uuid.UUID
}

func (req HandshakeRequest) OpCode() int16 {
	return 1
}

func CreateHandshakeRequest() HandshakeRequest {
	return HandshakeRequest{Code: 1, Major: 1, Minor: 7, Maintenance: 0, ClientType: 2}
}

func (req HandshakeRequest) Write(bw BinaryWriter) {
	bw.WriteByte(req.Code)
	bw.WriteInt16(req.Major)
	bw.WriteInt16(req.Minor)
	bw.WriteInt16(req.Maintenance)
	bw.WriteByte(req.ClientType)
	bw.WriteInt32(int32(len(req.Features)))
	for i := 0; i < len(req.Features); i++ {
		bw.WriteByte(req.Features[i])
	}
	for key, val := range req.UserAttributes {
		bw.WriteString(&key)
		bw.WriteString(val)
	}
	bw.WriteString(req.Username)
	bw.WriteString(req.Password)
}

func (req HandshakeRequest) ReadResponse(br BinaryReader) interface{} {
	resp := HandshakeResponse{}
	resp.Features = make([]byte, int(br.ReadInt32()))
	for i := 0; i < len(resp.Features); i++ {
		resp.Features[i] = br.ReadByte()
	}
	resp.NodeId = br.ReadUuid()
	return resp
}

type HandshakeFailResponse struct {
	Major       int16
	Minor       int16
	Maintenance int16
	Message     *string
	Code        byte
}

func (req HandshakeRequest) ReadFailResponse(br BinaryReader) interface{} {
	resp := HandshakeFailResponse{}
	resp.Major = br.ReadInt16()
	resp.Minor = br.ReadInt16()
	resp.Maintenance = br.ReadInt16()
	resp.Message = br.ReadString()
	resp.Code = br.ReadByte()
	return resp
}
