// Code generated by "gen_req_resp.go"; DO NOT EDIT.
package serdes

type HandshakeResponse struct {
	Code        byte
	Major       int16
	Minor       int16
	Maintenance int16
	Message     string
}

func CreateHandshakeResponse() HandshakeResponse {
	return HandshakeResponse{}
}

func (buf *IgniteBuffer) ReadHandshakeResponse() HandshakeResponse {
	var resp = CreateHandshakeResponse()

	resp.Code = buf.ReadByte()

	if buf.HashMore() {
		resp.Major = buf.ReadInt16()
		resp.Minor = buf.ReadInt16()
		resp.Maintenance = buf.ReadInt16()
		resp.Message = buf.ReadString()
	}

	return resp
}
