// Code generated by "gen_req_resp.go"; DO NOT EDIT.
package serdes

type HandshakeFailResponse struct {
	Major       int16
	Minor       int16
	Maintenance int16
	Message     *string
	Code        byte
}

func CreateHandshakeFailResponse() HandshakeFailResponse {
	return HandshakeFailResponse{}
}

func (buf *IgniteBuffer) ReadHandshakeFailResponse() HandshakeFailResponse {
	var resp = CreateHandshakeFailResponse()

	resp.Major = buf.ReadInt16()
	resp.Minor = buf.ReadInt16()
	resp.Maintenance = buf.ReadInt16()
	resp.Message = buf.ReadString()
	resp.Code = buf.ReadByte()

	return resp
}
