// Code generated by "gen_req_resp.go"; DO NOT EDIT.
package serdes

import "github.com/google/uuid"

type HandshakeResponse struct {
	Features *[]byte
	NodeId   *uuid.UUID
}

func CreateHandshakeResponse() HandshakeResponse {
	return HandshakeResponse{}
}

func (buf *IgniteBuffer) ReadHandshakeResponse() HandshakeResponse {
	var resp = CreateHandshakeResponse()

	resp.Features = buf.ReadByteArray()
	resp.NodeId = buf.ReadUuid()

	return resp
}
