// Code generated by "gen_req_resp.go"; DO NOT EDIT.
package serdes

func (buf *IgniteBuffer) WriteInt16Byte(m map[int16]byte) {
	buf.WriteByte(MAP)
	buf.WriteInt(len(m))

	for key, val := range m {
		buf.WriteInt16(key)
		buf.WriteByte(val)
	}
}

func (buf *IgniteBuffer) WriteInt16ByteArray(m map[int16][]byte) {
	buf.WriteByte(MAP)
	buf.WriteInt(len(m))

	for key, val := range m {
		buf.WriteInt16(key)
		buf.WriteByteArray(val)
	}
}

func (buf *IgniteBuffer) WriteInt16Int16(m map[int16]int16) {
	buf.WriteByte(MAP)
	buf.WriteInt(len(m))

	for key, val := range m {
		buf.WriteInt16(key)
		buf.WriteInt16(val)
	}
}

func (buf *IgniteBuffer) WriteInt16Int32(m map[int16]int32) {
	buf.WriteByte(MAP)
	buf.WriteInt(len(m))

	for key, val := range m {
		buf.WriteInt16(key)
		buf.WriteInt32(val)
	}
}

func (buf *IgniteBuffer) WriteInt16Int64(m map[int16]int64) {
	buf.WriteByte(MAP)
	buf.WriteInt(len(m))

	for key, val := range m {
		buf.WriteInt16(key)
		buf.WriteInt64(val)
	}
}

func (buf *IgniteBuffer) WriteInt16String(m map[int16]string) {
	buf.WriteByte(MAP)
	buf.WriteInt(len(m))

	for key, val := range m {
		buf.WriteInt16(key)
		buf.WriteString(val)
	}
}

func (buf *IgniteBuffer) WriteInt32Int16(m map[int32]int16) {
	buf.WriteByte(MAP)
	buf.WriteInt(len(m))

	for key, val := range m {
		buf.WriteInt32(key)
		buf.WriteInt16(val)
	}
}

func (buf *IgniteBuffer) WriteInt32Int32(m map[int32]int32) {
	buf.WriteByte(MAP)
	buf.WriteInt(len(m))

	for key, val := range m {
		buf.WriteInt32(key)
		buf.WriteInt32(val)
	}
}

func (buf *IgniteBuffer) WriteInt32Int64(m map[int32]int64) {
	buf.WriteByte(MAP)
	buf.WriteInt(len(m))

	for key, val := range m {
		buf.WriteInt32(key)
		buf.WriteInt64(val)
	}
}

func (buf *IgniteBuffer) WriteInt32String(m map[int32]string) {
	buf.WriteByte(MAP)
	buf.WriteInt(len(m))

	for key, val := range m {
		buf.WriteInt32(key)
		buf.WriteString(val)
	}
}

func (buf *IgniteBuffer) WriteInt32Byte(m map[int32]byte) {
	buf.WriteByte(MAP)
	buf.WriteInt(len(m))

	for key, val := range m {
		buf.WriteInt32(key)
		buf.WriteByte(val)
	}
}

func (buf *IgniteBuffer) WriteInt32ByteArray(m map[int32][]byte) {
	buf.WriteByte(MAP)
	buf.WriteInt(len(m))

	for key, val := range m {
		buf.WriteInt32(key)
		buf.WriteByteArray(val)
	}
}

func (buf *IgniteBuffer) WriteInt64Byte(m map[int64]byte) {
	buf.WriteByte(MAP)
	buf.WriteInt(len(m))

	for key, val := range m {
		buf.WriteInt64(key)
		buf.WriteByte(val)
	}
}

func (buf *IgniteBuffer) WriteInt64ByteArray(m map[int64][]byte) {
	buf.WriteByte(MAP)
	buf.WriteInt(len(m))

	for key, val := range m {
		buf.WriteInt64(key)
		buf.WriteByteArray(val)
	}
}

func (buf *IgniteBuffer) WriteInt64Int16(m map[int64]int16) {
	buf.WriteByte(MAP)
	buf.WriteInt(len(m))

	for key, val := range m {
		buf.WriteInt64(key)
		buf.WriteInt16(val)
	}
}

func (buf *IgniteBuffer) WriteInt64Int32(m map[int64]int32) {
	buf.WriteByte(MAP)
	buf.WriteInt(len(m))

	for key, val := range m {
		buf.WriteInt64(key)
		buf.WriteInt32(val)
	}
}

func (buf *IgniteBuffer) WriteInt64Int64(m map[int64]int64) {
	buf.WriteByte(MAP)
	buf.WriteInt(len(m))

	for key, val := range m {
		buf.WriteInt64(key)
		buf.WriteInt64(val)
	}
}

func (buf *IgniteBuffer) WriteInt64String(m map[int64]string) {
	buf.WriteByte(MAP)
	buf.WriteInt(len(m))

	for key, val := range m {
		buf.WriteInt64(key)
		buf.WriteString(val)
	}
}

func (buf *IgniteBuffer) WriteStringByte(m map[string]byte) {
	buf.WriteByte(MAP)
	buf.WriteInt(len(m))

	for key, val := range m {
		buf.WriteString(key)
		buf.WriteByte(val)
	}
}

func (buf *IgniteBuffer) WriteStringByteArray(m map[string][]byte) {
	buf.WriteByte(MAP)
	buf.WriteInt(len(m))

	for key, val := range m {
		buf.WriteString(key)
		buf.WriteByteArray(val)
	}
}

func (buf *IgniteBuffer) WriteStringInt16(m map[string]int16) {
	buf.WriteByte(MAP)
	buf.WriteInt(len(m))

	for key, val := range m {
		buf.WriteString(key)
		buf.WriteInt16(val)
	}
}

func (buf *IgniteBuffer) WriteStringInt32(m map[string]int32) {
	buf.WriteByte(MAP)
	buf.WriteInt(len(m))

	for key, val := range m {
		buf.WriteString(key)
		buf.WriteInt32(val)
	}
}

func (buf *IgniteBuffer) WriteStringInt64(m map[string]int64) {
	buf.WriteByte(MAP)
	buf.WriteInt(len(m))

	for key, val := range m {
		buf.WriteString(key)
		buf.WriteInt64(val)
	}
}

func (buf *IgniteBuffer) WriteStringString(m map[string]string) {
	buf.WriteByte(MAP)
	buf.WriteInt(len(m))

	for key, val := range m {
		buf.WriteString(key)
		buf.WriteString(val)
	}
}

func (buf *IgniteBuffer) WriteByteString(m map[byte]string) {
	buf.WriteByte(MAP)
	buf.WriteInt(len(m))

	for key, val := range m {
		buf.WriteByte(key)
		buf.WriteString(val)
	}
}

func (buf *IgniteBuffer) WriteByteByte(m map[byte]byte) {
	buf.WriteByte(MAP)
	buf.WriteInt(len(m))

	for key, val := range m {
		buf.WriteByte(key)
		buf.WriteByte(val)
	}
}

func (buf *IgniteBuffer) WriteByteByteArray(m map[byte][]byte) {
	buf.WriteByte(MAP)
	buf.WriteInt(len(m))

	for key, val := range m {
		buf.WriteByte(key)
		buf.WriteByteArray(val)
	}
}

func (buf *IgniteBuffer) WriteByteInt16(m map[byte]int16) {
	buf.WriteByte(MAP)
	buf.WriteInt(len(m))

	for key, val := range m {
		buf.WriteByte(key)
		buf.WriteInt16(val)
	}
}

func (buf *IgniteBuffer) WriteByteInt32(m map[byte]int32) {
	buf.WriteByte(MAP)
	buf.WriteInt(len(m))

	for key, val := range m {
		buf.WriteByte(key)
		buf.WriteInt32(val)
	}
}

func (buf *IgniteBuffer) WriteByteInt64(m map[byte]int64) {
	buf.WriteByte(MAP)
	buf.WriteInt(len(m))

	for key, val := range m {
		buf.WriteByte(key)
		buf.WriteInt64(val)
	}
}
