// Code generated by "gen_req_resp.go"; DO NOT EDIT.
package serdes

type CacheCreateWithNameRequest struct {
	Cache *string
}

type CacheCreateWithNameResponse struct {
}

func (req CacheCreateWithNameRequest) OpCode() int16 {
	return 1051
}

func (req CacheCreateWithNameRequest) Write(bw BinaryWriter) {
	bw.WriteString(req.Cache)
}

func (req CacheCreateWithNameRequest) ReadResponse(br BinaryReader) interface{} {
	resp := CacheCreateWithNameResponse{}
	return resp
}
