// Code generated by "gen_req_resp.go"; DO NOT EDIT.
package serdes

type CacheGetNamesRequest struct {
}

type CacheGetNamesResponse struct {
	Caches []*string
}

func (req CacheGetNamesRequest) OpCode() int16 {
	return 1050
}

func (req CacheGetNamesRequest) Write(bw BinaryWriter) {
}

func (req CacheGetNamesRequest) ReadResponse(br BinaryReader) interface{} {
	resp := CacheGetNamesResponse{}
	resp.Caches = make([]*string, int(br.ReadInt32()))
	for i := 0; i < len(resp.Caches); i++ {
		resp.Caches[i] = br.ReadString()
	}
	return resp
}
