// The following directive is necessary to make the package coherent:
//go:build ignore

// This program generates contributors.go. It can be invoked by running
// go generate
package main

import (
	"encoding/json"
	"fmt"
	"golang.org/x/text/cases"
	"golang.org/x/text/language"
	"os"
	"path/filepath"
	"strings"
)

const (
	TAB = "    "
)

var imports = map[string]string{
	"uuid": "github.com/google/uuid",
}

var simpleName = map[string]string{
	"byte[]": "ByteArray",
	"uuid":   "Uuid",
}

var typeMap = map[string]string{
	"byte":   "byte",
	"byte[]": "*[]byte",
	"short":  "int16",
	"int":    "int32",
	"long":   "int64",
	"string": "*string",
	"uuid":   "*uuid.UUID",
}

type Field struct {
	Name      string
	Type      string
	KeyType   string
	ValueType string
	Value     string
}

type Request struct {
	Fields   []Field
	Optional []Field
}

type Format struct {
	Type         string
	Name         string
	Code         int32
	Request      *Request
	Response     *Request
	FailResponse *Request
}

func main() {
	serdesDir := "./serdes"

	err := os.MkdirAll(serdesDir, os.ModePerm)
	if err != nil {
		panic(err)
	}

	generateMapsSerdes(serdesDir)
	generateFormats(serdesDir)
}

func generateMapsSerdes(serdesDir string) {
	fmt.Println("Generating maps serdes methods")

	f, err := os.Create(filepath.Join(serdesDir, "maps_serdes.go"))
	defer f.Close()
	if err != nil {
		panic(err)
	}

	line("// Code generated by \"gen_req_resp.go\"; DO NOT EDIT.", f)
	line("package serdes", f)
	line("", f)
	line("import \"github.com/google/uuid\"", f)
	line("", f)

	for keyType, goKeyType := range typeMap {
		if keyType == "byte[]" {
			continue
		}

		isGoKeyTypePointer := goKeyType[0] == '*'
		goKeyType = removePointer(goKeyType)

		for valType, goValType := range typeMap {
			isGoValTypePointer := goValType[0] == '*'
			goValType = removePointer(goValType)

			line(fmt.Sprintf("func (buf *IgniteBuffer) %s(m *map[%s]%s) {", mapWriteMethodName(keyType, valType), goKeyType, goValType), f)
			line(TAB+"if m == nil {", f)
			line(TAB+TAB+"buf.WriteByte(Null)", f)
			line(TAB+TAB+"return", f)
			line(TAB+"}", f)

			line(TAB+"buf.WriteByte(MAP)", f)
			line(TAB+"buf.WriteInt(len(*m))", f)
			line(TAB+"buf.WriteByte(1)", f)
			line("", f)
			line(TAB+"for key, val := range *m {", f)

			keyArg := "key"
			if isGoKeyTypePointer {
				keyArg = "&key"
			}

			valArg := "val"
			if isGoValTypePointer {
				valArg = "&val"
			}

			line(TAB+TAB+fmt.Sprintf("buf.%s(%s)", writeMethodName(keyType, nil), keyArg), f)

			line(TAB+TAB+fmt.Sprintf("buf.%s(%s)", writeMethodName(valType, nil), valArg), f)
			line(TAB+"}", f)

			line("}", f)
			line("", f)
		}
	}
}

func generateFormats(serdesDir string) {
	fmt.Println("Generating Ignite Thin Client request/response structs")
	files, err := filepath.Glob("../formats/*.json")
	if err != nil {
		panic(err)
	}

	for _, formatFile := range files {
		generateFrom(formatFile, serdesDir)
	}
}

func generateFrom(formatFile string, serdesDir string) {
	fmt.Printf("Process file [file=%s]", formatFile)
	fmt.Println()
	formatBytes, _ := os.ReadFile(formatFile)

	var desc Format

	err := json.Unmarshal(formatBytes, &desc)
	if err != nil {
		panic(err)
	}

	fmt.Printf("|--> request [name=%s]", desc.Name)
	fmt.Println()

	generateRequest(desc.Request, desc.Name, serdesDir)

	if desc.Response != nil {
		fmt.Printf("|--> response [name=%s]", desc.Name)
		fmt.Println()

		generateResponse(desc.Response, desc.Name, "_response.go", serdesDir)
	}

	if desc.FailResponse != nil {
		fmt.Printf("|--> fail response [name=%s]", desc.Name)
		fmt.Println()

		generateResponse(desc.FailResponse, desc.Name, "_fail_response.go", serdesDir)
	}
}

func generateRequest(request *Request, name string, serdesDir string) {
	f, err := os.Create(filepath.Join(serdesDir, name+"_request.go"))
	defer f.Close()
	if err != nil {
		panic(err)
	}

	line("// Code generated by \"gen_req_resp.go\"; DO NOT EDIT.", f)
	line("package serdes", f)
	line("", f)
	if generateImports(request, f) {
		line("", f)
	}

	var typeName string = exportedName(name) + "Request"

	genStruct(request, typeName, f)
	line("", f)
	genConstructor(request, typeName, f)
	line("", f)
	genWrite(request, typeName, f)
}

func generateImports(request *Request, f *os.File) bool {
	res := false

	addImport := func(fld Field) bool {
		imprt, contains := imports[fld.Type]
		if contains {
			line(fmt.Sprintf("import \"%s\"", imprt), f)
		}
		return contains
	}

	for _, fld := range request.Fields {
		res = res || addImport(fld)
	}

	for _, fld := range request.Optional {
		res = res || addImport(fld)
	}

	return res
}

func genStruct(request *Request, typeName string, f *os.File) {
	line(fmt.Sprintf("type %s struct {", typeName), f)

	for _, fld := range request.Fields {
		line(fmt.Sprintf(TAB+"%s %s", exportedName(fld.Name), goType(fld.Type, &fld)), f)
	}

	for _, fld := range request.Optional {
		line(fmt.Sprintf(TAB+"%s %s", exportedName(fld.Name), goType(fld.Type, &fld)), f)
	}

	line("}", f)
}

func genConstructor(request *Request, typeName string, f *os.File) {
	line(fmt.Sprintf("func %s() %s {", constructorName(typeName), typeName), f)

	var dfltVals string

	for _, fld := range request.Fields {
		if fld.Value != "" {
			if dfltVals != "" {
				dfltVals += ", "
			}
			dfltVals += fmt.Sprintf("%s: %s", exportedName(fld.Name), defaultValue(fld))
		}
	}

	line(fmt.Sprintf(TAB+"return %s{%s}", typeName, dfltVals), f)
	line("}", f)
}

func genWrite(request *Request, typeName string, f *os.File) {
	line(fmt.Sprintf("func (req *%s) Write(buf *IgniteBuffer) {", typeName), f)

	for _, fld := range request.Fields {
		line(fmt.Sprintf(TAB+"buf.%s(req.%s)", writeMethodName(fld.Type, &fld), exportedName(fld.Name)), f)
	}

	line("}", f)
}

func genRead(request *Request, typeName string, f *os.File) {
	line(fmt.Sprintf("func (buf *IgniteBuffer) Read%s() %s {", typeName, typeName), f)

	line(fmt.Sprintf(TAB+"var resp = %s()", constructorName(typeName)), f)
	line("", f)

	for _, fld := range request.Fields {
		line(fmt.Sprintf(TAB+"resp.%s = buf.%s()", exportedName(fld.Name), readMethodName(fld.Type)), f)
	}

	if len(request.Optional) > 0 {
		line("", f)
		line(TAB+"if buf.HasMore() {", f)

		for _, fld := range request.Optional {
			line(fmt.Sprintf(TAB+TAB+"resp.%s = buf.%s()", exportedName(fld.Name), readMethodName(fld.Type)), f)
		}

		line(TAB+"}", f)
	}

	line("", f)
	line(TAB+"return resp", f)
	line("}", f)
}

func generateResponse(request *Request, name string, pfx string, serdesDir string) {
	f, err := os.Create(filepath.Join(serdesDir, name+pfx))
	defer f.Close()
	if err != nil {
		panic(err)
	}

	line("// Code generated by \"gen_req_resp.go\"; DO NOT EDIT.", f)
	line("package serdes", f)
	line("", f)
	if generateImports(request, f) {
		line("", f)
	}

	var typeName string = exportedName(name)
	if pfx == "_response.go" {
		typeName += "Response"
	} else {
		typeName += "FailResponse"
	}

	genStruct(request, typeName, f)
	line("", f)
	genConstructor(request, typeName, f)
	line("", f)
	genRead(request, typeName, f)
}

func line(line string, file *os.File) {
	file.WriteString(line)
	file.WriteString("\n")
}

func writeMethodName(tp string, fld *Field) string {
	if fld != nil && fld.Type == "map" {
		keyTypeName, contains := simpleName[fld.KeyType]
		if !contains {
			keyTypeName = fld.KeyType
		}

		valTypeName, contains0 := simpleName[fld.ValueType]
		if !contains0 {
			valTypeName = fld.ValueType
		}

		return mapWriteMethodName(keyTypeName, valTypeName)
	}

	return methodName("Write", tp)
}

func mapWriteMethodName(keyType string, valType string) string {
	keyPart, contains := simpleName[keyType]
	if !contains {
		keyPart = exportedName(removePointer(goType(keyType, nil)))
	}
	valPart, contains := simpleName[valType]
	if !contains {
		valPart = exportedName(removePointer(goType(valType, nil)))
	}

	return fmt.Sprintf("Write%s%s", keyPart, valPart)
}

func readMethodName(tp string) string {
	return methodName("Read", tp)
}

func methodName(pfx string, tp string) string {
	name, contains := simpleName[tp]
	if !contains {
		goTp := removePointer(goType(tp, nil))

		return fmt.Sprintf("%s%s", pfx, exportedName(goTp))
	}
	return pfx + name
}

func constructorName(typeName string) string {
	return fmt.Sprintf("Create%s", typeName)
}

func exportedName(name string) string {
	return cases.Title(language.English, cases.NoLower).String(name)
}

func goType(tp string, fld *Field) string {
	if tp == "map" {
		if fld == nil {
			panic("fld is nil")
		}
		return fmt.Sprintf("*map[%s]%s", removePointer(goType(fld.KeyType, nil)), removePointer(goType(fld.ValueType, nil)))
	}

	res, ok := typeMap[tp]
	if !ok {
		panic(fmt.Sprintf("unknown type %s", tp))
	}
	return res
}

func defaultValue(fld Field) string {
	if fld.Type == "string" {
		return fmt.Sprintf("\"%s\"", fld.Value)
	}

	_, ok := typeMap[fld.Type]
	if !ok {
		panic("Unknown type " + fld.Type)
	}

	return fld.Value
}

func removePointer(tp string) string {
	if strings.HasPrefix(tp, "*") {
		return tp[1:]
	}

	return tp
}
